<?php
header("Content-Type: application/json; charset=UTF-8");
header("Content-Security-Policy: default-src 'none';");
header("X-Frame-Options: SAMEORIGIN");
header("x-content-type-options: nosniff");
header("Referrer-Policy: same-origin");
header("Strict-Transport-Security: max-age=31536000;");
header("Permissions-Policy: geolocation=(self)");
header_remove('X-Powered-By');
include "pdo-db.php";
$data = json_decode(file_get_contents("php://input"));
$response = array();
$accesskey = trim($data->accesskey);
$ipno = $data->ipno;
$atype = $data->atype;
$umr = $data->umr;
$captured_date_and_time = ($data->captured_date_and_time);
/* $captured_date_and_time = str_replace("/", " ", $captured_date_and_time); */
$bp_check_position_1 = strtoupper($data->bp_check_position_1);
$bp_dd_1 = $data->bp_dd_1;
$bp_systolic_1 = $data->bp_systolic_1;
$bp_diastolic_1 = $data->bp_diastolic_1;
$bp_check_position_2 = strtoupper($data->bp_check_position_2);
$bp_dd_2 = $data->bp_dd_2;
$bp_systolic_2 = $data->bp_systolic_2;
$bp_diastolic_2 = $data->bp_diastolic_2;
$bp_check_position_3 = strtoupper($data->bp_check_position_3);
$bp_dd_3 = $data->bp_dd_3;
$bp_systolic_3 = $data->bp_systolic_3;
$bp_diastolic_3 = $data->bp_diastolic_3;
$bp_units = $data->bp_units;
$pulse_dd = $data->pulse_dd;
$pulse_rate = $data->pulse_rate;
$pulse_units = $data->pulse_units;
$heart_rate_dd = $data->heart_rate_dd;
$heart_rate = $data->heart_rate;
$heart_rate_units = $data->heart_rate_units;
$respiratory_rate = $data->respiratory_rate;
$respiratory_units = $data->respiratory_units;
$weight = $data->weight;
$weight_units = $data->weight_units;
$height_rate = $data->height_rate;
$height_units = $data->height_units;
$bmi_rate = $data->bmi_rate;
$bmi_units = $data->bmi_units;
$bsa_rate = $data->bsa_rate;
$bsa_units = $data->bsa_units;
$temp_dd = $data->temp_dd;
$temp_rate = $data->temp_rate;
$temp_units = $data->temp_units;
$spo2_dd1 = $data->spo2_dd1;
$spo2_dd2 = $data->spo2_dd2;
$spo2_rate = $data->spo2_rate;
$pain_score = $data->pain_score;
$grbs = $data->grbs;
$grbs_units = $data->grbs_units;
$blood_group = $data->blood_group;
$fra_history = $data->fra_history;
$fra_history_response = $data->fra_history_response;
$fra_diagnosis = $data->fra_diagnosis;
$fra_diagnosis_response = $data->fra_diagnosis_response;
$fra_ambulatory = $data->fra_ambulatory;
$fra_ambulatory_response = $data->fra_ambulatory_response;
$fra_acess = $data->fra_acess;
$fra_access_response = $data->fra_access_response;
$fra_gait = $data->fra_gait;
$fra_gait_response = $data->fra_gait_response;
$fra_mental = $data->fra_mental;
$fra_mental_response = $data->fra_mental_response;
$fra_total = $data->fra_total;
$nursing_assessment = $data->nursing_assessment;
$goal = $data->goal;
$planning = $data->planning;
$implementation = $data->implementation;
$evaluation = $data->evaluation;
$pain_scale_type = $data->pain_scale_type;
$painscale_score = $data->painscale_score;
$doctor_name = $data->doctor_name;
$pain = $data->pain;
$pain_location = $data->pain_location;
$pain_character = $data->pain_character;
$pain_duration_type = $data->pain_duration_type;
$pain_duration = $data->pain_duration;
$factor_decreasing_pain = $data->factor_decreasing_pain;
$factor_increasing_pain = $data->factor_increasing_pain;
$action_plan = $data->action_plan;
$intervention = $data->intervention;
$intervention_therapy = $data->intervention_therapy;
$heparin_therapy = $data->heparin_therapy;
$facial_expression = $data->facial_expression;
$upper_limb_movements = $data->upper_limb_movements;
$compliance_mechanical_ventilation = $data->compliance_mechanical_ventilation;
$allergies_medication = $data->allergies_medication;
$allergies_medication_data = $data->allergies_medication_data;
$food = $data->food;
$food_data = $data->food_data;
$other_allergies = $data->other_allergies;
$rep_bradypnea = $data->rep_bradypnea;
$rep_bradypnea_response = $data->rep_bradypnea_response;
$rep_dyspnea = $data->rep_dyspnea;
$rep_dyspnea_response = $data->rep_dyspnea_response;
$rep_laboured = $data->rep_laboured;
$rep_laboured_response = $data->rep_laboured_response;
$rep_normal = $data->rep_normal;
$rep_normal_response = $data->rep_normal_response;
$rep_tachypnea = $data->rep_tachypnea;
$rep_tachypnea_response = $data->rep_tachypnea_response;
$rep_tracheostomya = $data->rep_tracheostomya;
$rep_tracheostomy_response = $data->rep_tracheostomy_response;
$rep_ventilator = $data->rep_ventilator;
$rep_ventilator_response = $data->rep_ventilator_response;
$cough_absent = $data->cough_absent;
$cough_absent_response = $data->cough_absent_response;
$cough_present = $data->cough_present;
$cough_present_response = $data->cough_present_response;
$cough_non_productive = $data->cough_non_productive;
$cough_non_productive_response = $data->cough_non_productive_response;
$cough_productive = $data->cough_productive;
$cough_productive_response = $data->cough_productive_response;
$cough_others = $data->cough_others;
$gi_bleeding = $data->gi_bleeding;
$gi_bleeding_response = $data->gi_bleeding_response;
$gi_constipation = $data->gi_constipation;
$gi_constipation_response = $data->gi_constipation_response;
$gi_diarrhoea = $data->gi_diarrhoea;
$gi_diarrhoea_response = $data->gi_diarrhoea_response;
$gi_hematemesis = $data->gi_hematemesis;
$gi_hematemesis_response = $data->gi_hematemesis_response;
$gi_malena = $data->gi_malena;
$gi_malena_response = $data->gi_malena_response;
$gi_nausea_vomiting = $data->gi_nausea_vomiting;
$gi_nausea_vomiting_response = $data->gi_nausea_vomiting_response;
$gi_others = $data->gi_others;
$ms_fracture = $data->ms_fracture;
$ms_fracture_response = $data->ms_fracture_response;
$ms_joint_stiffness = $data->ms_joint_stiffness;
$ms_joint_stiffness_response = $data->ms_joint_stiffness_response;
$ms_musleatropy = $data->ms_musleatropy;
$ms_musleatropy_response = $data->ms_musleatropy_response;
$ms_paralysis = $data->ms_paralysis;
$ms_paralysis_response = $data->ms_paralysis_response;
$ms_swelling = $data->ms_swelling;
$ms_swelling_response = $data->ms_swelling_response;
$ms_traction = $data->ms_traction;
$ms_traction_response = $data->ms_traction_response;
$ms_vitals_signs = $data->ms_vitals_signs;
$ms_vitals_signs_response = $data->ms_vitals_signs_response;
$ms_wound = $data->ms_wound;
$ms_wound_response = $data->ms_wound_response;
$behaviour_total = $data->behaviour_total;
//=$data->phase2
$category2 = trim($data->category2);
$is_altered_sensorium = trim($data->is_altered_sensorium);
$altered_sensorium = trim($data->altered_sensorium);
$is_facialpalsyasymmetry = trim($data->is_facialpalsyasymmetry);
$facialpalsyasymmetry = trim($data->facialpalsyasymmetry);
$is_impairedgait = trim($data->is_impairedgait);
$impairedgait = trim($data->impairedgait);
$isnumbne = trim($data->isnumbne);
$numbnes = trim($data->numbnes);
$is_paralysi = trim($data->is_paralysi);
$paralysi = trim($data->paralysi);
$istingling = trim($data->istingling);
$tingling = trim($data->tingling);
$isvertigo = trim($data->isvertigo);
$vertigo = trim($data->vertigo);
$weakness = trim($data->weakness);
$paresis = trim($data->paresis);
$rightpupilsize = trim($data->rightpupilsize);
$leftpupilsize = trim($data->leftpupilsize);
$scleracolorwhite = trim($data->scleracolorwhite);
$pupillaryreactionright = trim($data->pupillaryreactionright);
$pupillaryreactionleft = trim($data->pupillaryreactionleft);
$othersphas2 = trim($data->othersphas2);
$pressure_ulcer_category = trim($data->pressure_ulcer_category);
$antomy_location_of_wound = trim($data->antomy_location_of_wound);
$age_of_wound = trim($data->age_of_wound);
$size_of_wound = trim($data->size_of_wound);
$depth_of_ulcer = trim($data->depth_of_ulcer);
$stage_of_ulcer = trim($data->stage_of_ulcer);
$exu_dates = trim($data->exu_dates);
$pressure_ulcer_remarks = trim($data->pressure_ulcer_remarks);
$predicting_a1 = trim($data->predicting_a1);
$predicting_a2 = trim($data->predicting_a2);
$predicting_a3 = trim($data->predicting_a3);
$predicting_a4 = trim($data->predicting_a4);
$predicting_a5 = trim($data->predicting_a5);
$predicting_a6 = trim($data->predicting_a6);
$predicting_total = trim($data->predicting_total);
$urinary_a1 = trim($data->urinary_a1);
$urinary_a1_res = trim($data->urinary_a1_res);
$urinary_a2 = trim($data->urinary_a2);
$urinary_a2_res = trim($data->urinary_a2_res);
$urinary_a3 = trim($data->urinary_a3);
$urinary_a3_res = trim($data->urinary_a3_res);
$urinary_a4 = trim($data->urinary_a4);
$urinary_a4_res = trim($data->urinary_a4_res);
$urinary_a5 = trim($data->urinary_a5);
$urinary_a5_res = trim($data->urinary_a5_res);
$urinary_a6 = trim($data->urinary_a6);
$urinary_a6_res = trim($data->urinary_a6_res);
$urinary_a7 = trim($data->urinary_a7);
$urinary_a7_res = trim($data->urinary_a7_res);
$urinary_a8 = trim($data->urinary_a8);
$urinary_a8_res = trim($data->urinary_a8_res);
$cardio_breathlessness = trim($data->cardio_breathlessness);
$cardio_notes = trim($data->cardio_notes);
$chest_discomfort = trim($data->chest_discomfort);
$chest_notes = trim($data->chest_notes);
$clubbing_fingers = trim($data->clubbing_fingers);
$clubbing_fingers_notes = trim($data->clubbing_fingers_notes);
$edema = trim($data->edema);
$cardio_fatigue = trim($data->cardio_fatigue);
$fatigue_notes = trim($data->fatigue_notes);
$orthopnea = trim($data->orthopnea);
$orthopnea_notes = trim($data->orthopnea_notes);
$palpitation = trim($data->palpitation);
$palpitation_notes = trim($data->palpitation_notes);
$cardio_sweating = trim($data->cardio_sweating);
$sweating_notes = trim($data->sweating_notes);
$syncope = trim($data->syncope);
$syncope_notes = trim($data->syncope_notes);
$tachycardia = trim($data->tachycardia);
$tachycardia_notes = trim($data->tachycardia_notes);
$cardio_others = trim($data->cardio_others);
$jaundiced = trim($data->jaundiced);
$jaundiced_notes = trim($data->jaundiced_notes);
$pale = trim($data->pale);
$pale_notes = trim($data->pale_notes);
$pink = trim($data->pink);
$pink_notes = trim($data->pink_notes);
$purpura = trim($data->purpura);
$purpura_notes = trim($data->purpura_notes);
$cyanosis = trim($data->cyanosis);
$cyanosis_notes = trim($data->cyanosis_notes);
$above_three_seconds = trim($data->above_three_seconds);
$above_three_seconds_notes = trim($data->above_three_seconds_notes);
$below_three_seconds = trim($data->below_three_seconds);
$below_three_seconds_notes = trim($data->below_three_seconds_notes);
$edema_notes = trim($data->edema_notes);

//phase 3 2
$l1 = trim($data->l1);
$l2 = trim($data->l2);
$l3 = trim($data->l3);
$l4 = trim($data->l4);
$m1 = trim($data->m1);
$m2 = trim($data->m2);
$m3 = trim($data->m3);
$m4 = trim($data->m4);
$n1 = trim($data->n1);
$n2 = trim($data->n2);
$n3 = trim($data->n3);
$n4 = trim($data->n4);
$o1 = trim($data->o1);
$o2 = trim($data->o2);
$o3 = trim($data->o3);
$o4 = trim($data->o4);
$p1 = trim($data->p1);
$p2 = trim($data->p2);
$p3 = trim($data->p3);
$p4 = trim($data->p4);
$q1 = trim($data->q1);
$q2 = trim($data->q2);
$q3 = trim($data->q3);
$q4 = trim($data->q4);
$r1 = trim($data->r1);
$r2 = trim($data->r2);
$r3 = trim($data->r3);
$r4 = trim($data->r4);
$s1 = trim($data->s1);
$s2 = trim($data->s2);
$s3 = trim($data->s3);
$s4 = trim($data->s4);
$t1 = trim($data->t1);
$t2 = trim($data->t2);
$t3 = trim($data->t3);
$t4 = trim($data->t4);
$u1 = trim($data->u1);
$u2 = trim($data->u2);
$u3 = trim($data->u3);
$u4 = trim($data->u4);
$v1 = trim($data->v1);
$v2 = trim($data->v2);
$v3 = trim($data->v3);
$v4 = trim($data->v4);

$a1 = trim($data->a1);
$a2 = trim($data->a2);
$a3 = trim($data->a3);
$a4 = trim($data->a4);
$b1 = trim($data->b1);
$b2 = trim($data->b2);
$b3 = trim($data->b3);
$b4 = trim($data->b4);
$c1 = trim($data->c1);
$c2 = trim($data->c2);
$c3 = trim($data->c3);
$c4 = trim($data->c4);
$d1 = trim($data->d1);
$d2 = trim($data->d2);
$d3 = trim($data->d3);
$d4 = trim($data->d4);
$e1 = trim($data->e1);
$e2 = trim($data->e2);
$e3 = trim($data->e3);
$e4 = trim($data->e4);
$f1 = trim($data->f1);
$f2 = trim($data->f2);
$f3 = trim($data->f3);
$f4 = trim($data->f4);
$g1 = trim($data->g1);
$g2 = trim($data->g2);
$g3 = trim($data->g3);
$g4 = trim($data->g4);
$h1 = trim($data->h1);
$h2 = trim($data->h2);
$h3 = trim($data->h3);
$h4 = trim($data->h4);
$i1 = trim($data->i1);
$i2 = trim($data->i2);
$i3 = trim($data->i3);
$i4 = trim($data->i4);
$j1 = trim($data->j1);
$j2 = trim($data->j2);
$j3 = trim($data->j3);
$j4 = trim($data->j4);
$k1 = trim($data->k1);
$k2 = trim($data->k2);
$k3 = trim($data->k3);
$k4 = trim($data->k4);

$motor_response_score = trim($data->motor_response_score);
$verbal_response_score = trim($data->verbal_response_score);
$eye_opening_score = trim($data->eye_opening_score);
$glasgowtotal = trim($data->glasgowtotal);

$ipaddress = $_SERVER['REMOTE_ADDR'];
$apiurl = substr($_SERVER["SCRIPT_NAME"], strrpos($_SERVER["SCRIPT_NAME"], "/") + 1);
$mybrowser = get_browser(null, true);
try {
    if (!empty($accesskey) && !empty($ipno)) {
       
        $check = $pdoread->prepare("SELECT `userid`,`cost_center` FROM `user_logins` WHERE `mobile_accesskey` = :accesskey AND `status` = 'Active'");
        $check->bindParam(':accesskey', $accesskey, PDO::PARAM_STR);
        $check->execute();
        $result = $check->fetch(PDO::FETCH_ASSOC);
        if ($check->rowCount() > 0) {

            //check patient discharged or not on ip
            $check_ip = $pdoread->prepare("SELECT `admissionno` FROM `registration` WHERE `admissionstatus` NOT IN('Discharged') AND `status`='Visible' AND `admissionno`=:ipno ");
            $check_ip->bindParam(':ipno', $ipno, PDO::PARAM_STR);
            $check_ip->execute();
            if ($check_ip->rowCount() > 0) {

                $nid = $pdoread->prepare("SELECT IFNULL(MAX(`nursing_id`),CONCAT('NID',DATE_FORMAT(CURRENT_DATE,'%y%m'),'000000')) AS nursing_id FROM `nursing_re_assessment_table` WHERE `nursing_id` LIKE '%NID%' ");
                $nid->execute();
                if ($nid->rowCount() > 0) {
                    $res = $nid->fetch(PDO::FETCH_ASSOC);
                    $nursing = $res['nursing_id'];
                    $nursingid = ++$nursing;

                    $page_id = $pdoread->prepare("SELECT IFNULL(MAX(`page_id`),CONCAT('IR',DATE_FORMAT(CURRENT_DATE,'%y%m'),'00000')) AS page_id  FROM `vital_signs_table` WHERE `page_id` LIKE '%IR%'");
                    $page_id->execute();
                    if ($page_id->rowCount() > 0) {
                        $pgid = $page_id->fetch(PDO::FETCH_ASSOC);
                        $pageid =  $pgid['page_id'];
                        $pgids = ++$pageid;
                    } else {
                        $pgids = $pgidno;
                    }
                    //nursing id created
                    //insert into the table
                    $ninsert = $pdo4->prepare("INSERT IGNORE INTO `nursing_re_assessment_table`(`sno`, `admission_num`, `umr_no`,`nursing_id`,  `assessment_type`,  `vital_sign_id`, `fra_history`, `fra_history_response`, `fra_diagnosis`, `fra_diagnosis_response`, `fra_ambulatory`, `fra_ambulatory_response`, `fra_acess`, `fra_access_response`, `fra_gait`, `fra_gait_response`, `fra_mental`, `fra_mental_response`,`fra_total`, `nursing_assessment`, `goal`, `planning`, `implementation`, `evaluation`, `pain_id`, `facial_expression`,`upper_limb_movements`,`compliance_mechanical_ventilation`,`allergies_medication`, `allergies_medication_data`, `food`, `food_data`, `other_allergies`, `rep_bradypnea`, `rep_bradypnea_response`, `rep_dyspnea`, `rep_dyspnea_response`, `rep_laboured`, `rep_laboured_response`, `rep_normal`, `rep_normal_response`, `rep_tachypnea`, `rep_tachypnea_response`, `rep_tracheostomya`, `rep_tracheostomy_response`, `rep_ventilator`, `rep_ventilator_response`, `cough_absent`, `cough_absent_response`, `cough_present`, `cough_present_response`, `cough_non_productive`, `cough_non_productive_response`, `cough_productive`, `cough_productive_response`, `cough_others`, `gi_bleeding`, `gi_bleeding_response`, `gi_constipation`, `gi_constipation_response`, `gi_diarrhoea`, `gi_diarrhoea_response`, `gi_hematemesis`, `gi_hematemesis_response`, `gi_malena`, `gi_malena_response`, `gi_nausea_vomiting`, `gi_nausea_vomiting_response`, `gi_others`, `ms_fracture`, `ms_fracture_response`, `ms_joint_stiffness`, `ms_joint_stiffness_response`, `ms_musleatropy`, `ms_musleatropy_response`, `ms_paralysis`, `ms_paralysis_response`, `ms_swelling`, `ms_swelling_response`, `ms_traction`, `ms_traction_response`, `ms_vitals_signs`, `ms_vitals_signs_response`, `ms_wound`, `ms_wound_response`, `ms_Others`, `estatus`, `created_on`, `created_by`, `modified_on`, `modified_by`, `cost_center`, `ip`, `assessment_id`,`behaviour_total`, `motor_response_score`, `verbal_response_score`, `eye_opening_score`, `glasgowtotal`) VALUES (NULL,:ipno,:umr,:nid,:atype, :vital_sign_id,
:fra_history,:fra_history_response,:fra_diagnosis,:fra_diagnosis_response,:fra_ambulatory,:fra_ambulatory_response,
:fra_acess,:fra_access_response,:fra_gait,:fra_gait_response,:fra_mental,:fra_mental_response,:fra_total,:nursing_assessment,:goal,:planning,:implementation,:evaluation, :vital_sign_id, :facial_expression, :upper_limb_movements,:compliance_mechanical_ventilation, :allergies_medication,:allergies_medication_data,:food,:food_data,:other_allergies,:rep_bradypnea,:rep_bradypnea_response, :rep_dyspnea, :rep_dyspnea_response, :rep_laboured, :rep_laboured_response, :rep_normal, :rep_normal_response, :rep_tachypnea, :rep_tachypnea_response,:rep_tracheostomya, :rep_tracheostomy_response, :rep_ventilator, :rep_ventilator_response, :cough_absent, :cough_absent_response, :cough_present, :cough_present_response, :cough_non_productive, :cough_non_productive_response, :cough_productive, :cough_productive_response, :cough_others, :gi_bleeding, :gi_bleeding_response, :gi_constipation, :gi_constipation_response, :gi_diarrhoea, :gi_diarrhoea_response, :gi_hematemesis, :gi_hematemesis_response, :gi_malena, :gi_malena_response, :gi_nausea_vomiting, :gi_nausea_vomiting_response, :gi_others, :ms_fracture, :ms_fracture_response, :ms_joint_stiffness, :ms_joint_stiffness_response, :ms_musleatropy, :ms_musleatropy_response, :ms_paralysis, :ms_paralysis_response, :ms_swelling, :ms_swelling_response, :ms_traction, :ms_traction_response, :ms_vitals_signs, :ms_vitals_signs_response, :ms_wound, :ms_wound_response, :ms_Others, 'Active',CURRENT_TIMESTAMP,:userid,CURRENT_TIMESTAMP,:userid,:costcenter,:ip, '0',:behaviour_total, :motor_response_score, :verbal_response_score, :eye_opening_score, :glasgowtotal) ");
                    $ninsert->bindParam(':ipno', $ipno, PDO::PARAM_STR);
                    $ninsert->bindParam(':nid', $nursingid, PDO::PARAM_STR);
                    $ninsert->bindParam(':atype', $atype, PDO::PARAM_STR);
                    $ninsert->bindParam(':vital_sign_id', $pgids, PDO::PARAM_STR);
                    $ninsert->bindParam(':umr', $umr, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_history', $fra_history, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_history_response', $fra_history_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_diagnosis', $fra_diagnosis, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_diagnosis_response', $fra_diagnosis_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_ambulatory', $fra_ambulatory, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_ambulatory_response', $fra_ambulatory_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_acess', $fra_acess, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_access_response', $fra_access_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_gait', $fra_gait, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_gait_response', $fra_gait_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_mental', $fra_mental, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_mental_response', $fra_mental_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':fra_total', $fra_total, PDO::PARAM_STR);
                    $ninsert->bindParam(':nursing_assessment', $nursing_assessment, PDO::PARAM_STR);
                    $ninsert->bindParam(':goal', $goal, PDO::PARAM_STR);
                    $ninsert->bindParam(':planning', $planning, PDO::PARAM_STR);
                    $ninsert->bindParam(':implementation', $implementation, PDO::PARAM_STR);
                    $ninsert->bindParam(':evaluation', $evaluation, PDO::PARAM_STR);
                    $ninsert->bindParam(':facial_expression', $facial_expression, PDO::PARAM_STR);
                    $ninsert->bindParam(':upper_limb_movements', $upper_limb_movements, PDO::PARAM_STR);
                    $ninsert->bindParam(':compliance_mechanical_ventilation', $compliance_mechanical_ventilation, PDO::PARAM_STR);
                    $ninsert->bindParam(':allergies_medication', $allergies_medication, PDO::PARAM_STR);
                    $ninsert->bindParam(':allergies_medication_data', $allergies_medication_data, PDO::PARAM_STR);
                    $ninsert->bindParam(':food', $food, PDO::PARAM_STR);
                    $ninsert->bindParam(':food_data', $food_data, PDO::PARAM_STR);
                    $ninsert->bindParam(':other_allergies', $other_allergies, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_bradypnea', $rep_bradypnea, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_bradypnea_response', $rep_bradypnea_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_dyspnea', $rep_dyspnea, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_dyspnea_response', $rep_dyspnea_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_laboured', $rep_laboured, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_laboured_response', $rep_laboured_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_normal', $rep_normal, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_normal_response', $rep_normal_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_tachypnea', $rep_tachypnea, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_tachypnea_response', $rep_tachypnea_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_tracheostomya', $rep_tracheostomya, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_tracheostomy_response', $rep_tracheostomy_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_ventilator', $rep_ventilator, PDO::PARAM_STR);
                    $ninsert->bindParam(':rep_ventilator_response', $rep_ventilator_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_absent', $cough_absent, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_absent_response', $cough_absent_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_present', $cough_present, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_present_response', $cough_present_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_non_productive', $cough_non_productive, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_non_productive_response', $cough_non_productive_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_productive', $cough_productive, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_productive_response', $cough_productive_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':cough_others', $cough_others, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_bleeding', $gi_bleeding, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_bleeding_response', $gi_bleeding_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_constipation', $gi_constipation, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_constipation_response', $gi_constipation_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_diarrhoea', $gi_diarrhoea, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_diarrhoea_response', $gi_diarrhoea_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_hematemesis', $gi_hematemesis, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_hematemesis_response', $gi_hematemesis_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_malena', $gi_malena, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_malena_response', $gi_malena_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_nausea_vomiting', $gi_nausea_vomiting, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_nausea_vomiting_response', $gi_nausea_vomiting_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':gi_others', $gi_others, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_fracture', $ms_fracture, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_fracture_response', $ms_fracture_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_joint_stiffness', $ms_joint_stiffness, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_joint_stiffness_response', $ms_joint_stiffness_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_musleatropy', $ms_musleatropy, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_musleatropy_response', $ms_musleatropy_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_paralysis', $ms_paralysis, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_paralysis_response', $ms_paralysis_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_swelling', $ms_swelling, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_swelling_response', $ms_swelling_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_traction', $ms_traction, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_traction_response', $ms_traction_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_vitals_signs', $ms_vitals_signs, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_vitals_signs_response', $ms_vitals_signs_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_wound', $ms_wound, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_wound_response', $ms_wound_response, PDO::PARAM_STR);
                    $ninsert->bindParam(':ms_Others', $ms_Others, PDO::PARAM_STR); //3rd module end
                    $ninsert->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
                    $ninsert->bindParam(':costcenter', $result['cost_center'], PDO::PARAM_STR);
                    $ninsert->bindParam(':ip', $ipaddress, PDO::PARAM_STR);
                    $ninsert->bindParam(':behaviour_total', $behaviour_total, PDO::PARAM_STR);
                    $ninsert->bindParam(':motor_response_score', $motor_response_score, PDO::PARAM_STR);
                    $ninsert->bindParam(':verbal_response_score', $verbal_response_score, PDO::PARAM_STR);
                    $ninsert->bindParam(':eye_opening_score', $eye_opening_score, PDO::PARAM_STR);
                    $ninsert->bindParam(':glasgowtotal', $glasgowtotal, PDO::PARAM_STR);
                    $ninsert->execute();
                    //phase 2
                    $phase2 = $pdo4->prepare("INSERT IGNORE INTO `systemic_assesment`(`serialno`, `ip_no`, `umr_no`, `category`, `is_altered_sensorium`, `altered_sensorium`, `is_facialpalsyasymmetry`, `facialpalsyasymmetry`, `is_impairedgait`, `impairedgait`, `isnumbne`, `numbnes`, `is_paralysi`, `paralysi`, `istingling`, `tingling`, `isvertigo`, `vertigo`, `weakness`, `paresis`, `rightpupilsize`, `leftpupilsize`, `scleracolorwhite`, `pupillaryreactionright`, `pupillaryreactionleft`, `others`, `cardio_breathlessness`, `cardio_notes`, `chest_discomfort`, `chest_notes`, `clubbing_fingers`, `clubbing_fingers_notes`, `edema`, `edema_notes`, `cardio_fatigue`, `fatigue_notes`, `orthopnea`, `orthopnea_notes`, `palpitation`, `palpitation_notes`, `cardio_sweating`, `sweating_notes`, `syncope`, `syncope_notes`, `tachycardia`, `tachycardia_notes`, `cardio_others`, `jaundiced`, `jaundiced_notes`, `pale`, `pale_notes`, `pink`, `pink_notes`, `purpura`, `purpura_notes`, `cyanosis`, `cyanosis_notes`, `above_three_seconds`, `above_three_seconds_notes`, `below_three_seconds`, `below_three_seconds_notes`, `pressure_ulcer_category`, `antomy_location_of_wound`, `age_of_wound`, `size_of_wound`, `depth_of_ulcer`, `stage_of_ulcer`, `exu_dates`, `pressure_ulcer_remarks`, `predicting_a1`, `predicting_a2`, `predicting_a3`, `predicting_a4`, `predicting_a5`, `predicting_a6`,`predicting_total`, `urinary_a1`, `urinary_a1_res`, `urinary_a2`, `urinary_a2_res`, `urinary_a3`, `urinary_a3_res`, `urinary_a4`, `urinary_a4_res`, `urinary_a5`, `urinary_a5_res`, `urinary_a6`, `urinary_a6_res`, `urinary_a7`, `urinary_a7_res`, `urinary_a8`, `urinary_a8_res`, `createdon`, `createdby`, `modifiedon`, `modifiedby`, `estatus`) VALUES (NULL,:ip_no,:umr_no,:category2,:is_altered_sensorium,:altered_sensorium,:is_facialpalsyasymmetry,:facialpalsyasymmetry,:is_impairedgait,:impairedgait,:isnumbne,:numbnes,:is_paralysi,:paralysi,:istingling,:tingling,:isvertigo,:vertigo,:weakness,:paresis,:rightpupilsize,:leftpupilsize,:scleracolorwhite,:pupillaryreactionright,:pupillaryreactionleft,:othersphas2,
:cardio_breathlessness,:cardio_notes,:chest_discomfort,:chest_notes,:clubbing_fingers,:clubbing_fingers_notes,:edema,:edema_notes,:cardio_fatigue,:fatigue_notes,:orthopnea,:orthopnea_notes,:palpitation,:palpitation_notes,:cardio_sweating,:sweating_notes,:syncope,:syncope_notes,:tachycardia,:tachycardia_notes,:cardio_others,:jaundiced,:jaundiced_notes,:pale,:pale_notes,:pink,:pink_notes,:purpura,:purpura_notes,:cyanosis,:cyanosis_notes,:above_three_seconds,:above_three_seconds_notes,:below_three_seconds,:below_three_seconds_notes,:pressure_ulcer_category,:antomy_location_of_wound,:age_of_wound,:size_of_wound,:depth_of_ulcer,:stage_of_ulcer,:exu_dates,:pressure_ulcer_remarks,:predicting_a1,:predicting_a2,:predicting_a3,:predicting_a4,:predicting_a5,:predicting_a6,:predicting_total,:urinary_a1,:urinary_a1_res,:urinary_a2,:urinary_a2_res,:urinary_a3,:urinary_a3_res,:urinary_a4,:urinary_a4_res,:urinary_a5,:urinary_a5_res,:urinary_a6,:urinary_a6_res,:urinary_a7,:urinary_a7_res,:urinary_a8,:urinary_a8_res,CURRENT_TIMESTAMP,:userid,CURRENT_TIMESTAMP,:userid,'Active')");
                    $phase2->bindParam(':ip_no', $ipno, PDO::PARAM_STR);
                    $phase2->bindParam(':umr_no', $umr, PDO::PARAM_STR);
                    $phase2->bindParam(':category2', $category2, PDO::PARAM_STR);
                    $phase2->bindParam(':is_altered_sensorium', $is_altered_sensorium, PDO::PARAM_STR);
                    $phase2->bindParam(':altered_sensorium', $altered_sensorium, PDO::PARAM_STR);
                    $phase2->bindParam(':is_facialpalsyasymmetry', $is_facialpalsyasymmetry, PDO::PARAM_STR);
                    $phase2->bindParam(':facialpalsyasymmetry', $facialpalsyasymmetry, PDO::PARAM_STR);
                    $phase2->bindParam(':is_impairedgait', $is_impairedgait, PDO::PARAM_STR);
                    $phase2->bindParam(':impairedgait', $impairedgait, PDO::PARAM_STR);
                    $phase2->bindParam(':isnumbne', $isnumbne, PDO::PARAM_STR);
                    $phase2->bindParam(':numbnes', $numbnes, PDO::PARAM_STR);
                    $phase2->bindParam(':is_paralysi', $is_paralysi, PDO::PARAM_STR);
                    $phase2->bindParam(':paralysi', $paralysi, PDO::PARAM_STR);
                    $phase2->bindParam(':istingling', $istingling, PDO::PARAM_STR);
                    $phase2->bindParam(':tingling', $tingling, PDO::PARAM_STR);
                    $phase2->bindParam(':isvertigo', $isvertigo, PDO::PARAM_STR);
                    $phase2->bindParam(':vertigo', $vertigo, PDO::PARAM_STR);
                    $phase2->bindParam(':weakness', $weakness, PDO::PARAM_STR);
                    $phase2->bindParam(':paresis', $paresis, PDO::PARAM_STR);
                    $phase2->bindParam(':rightpupilsize', $rightpupilsize, PDO::PARAM_STR);
                    $phase2->bindParam(':leftpupilsize', $leftpupilsize, PDO::PARAM_STR);
                    $phase2->bindParam(':scleracolorwhite', $scleracolorwhite, PDO::PARAM_STR);
                    $phase2->bindParam(':pupillaryreactionright', $pupillaryreactionright, PDO::PARAM_STR);
                    $phase2->bindParam(':pupillaryreactionleft', $pupillaryreactionleft, PDO::PARAM_STR);
                    $phase2->bindParam(':othersphas2', $othersphas2, PDO::PARAM_STR);
                    $phase2->bindParam(':pressure_ulcer_category', $pressure_ulcer_category, PDO::PARAM_STR);
                    $phase2->bindParam(':antomy_location_of_wound', $antomy_location_of_wound, PDO::PARAM_STR);
                    $phase2->bindParam(':age_of_wound', $age_of_wound, PDO::PARAM_STR);
                    $phase2->bindParam(':size_of_wound', $size_of_wound, PDO::PARAM_STR);
                    $phase2->bindParam(':depth_of_ulcer', $depth_of_ulcer, PDO::PARAM_STR);
                    $phase2->bindParam(':stage_of_ulcer', $stage_of_ulcer, PDO::PARAM_STR);
                    $phase2->bindParam(':exu_dates', $exu_dates, PDO::PARAM_STR);
                    $phase2->bindParam(':pressure_ulcer_remarks', $pressure_ulcer_remarks, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_a1', $predicting_a1, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_a2', $predicting_a2, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_a3', $predicting_a3, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_a4', $predicting_a4, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_a5', $predicting_a5, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_a6', $predicting_a6, PDO::PARAM_STR);
                    $phase2->bindParam(':predicting_total', $predicting_total, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a1', $urinary_a1, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a1_res', $urinary_a1_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a2', $urinary_a2, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a2_res', $urinary_a2_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a3', $urinary_a3, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a3_res', $urinary_a3_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a4', $urinary_a4, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a4_res', $urinary_a4_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a5', $urinary_a5, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a5_res', $urinary_a5_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a6', $urinary_a6, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a6_res', $urinary_a6_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a7', $urinary_a7, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a7_res', $urinary_a7_res, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a8', $urinary_a8, PDO::PARAM_STR);
                    $phase2->bindParam(':urinary_a8_res', $urinary_a8_res, PDO::PARAM_STR);
                    $phase2->bindParam(':edema_notes', $edema_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':cardio_breathlessness', $cardio_breathlessness, PDO::PARAM_STR);
                    $phase2->bindParam(':cardio_notes', $cardio_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':chest_discomfort', $chest_discomfort, PDO::PARAM_STR);
                    $phase2->bindParam(':chest_notes', $chest_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':clubbing_fingers', $clubbing_fingers, PDO::PARAM_STR);
                    $phase2->bindParam(':clubbing_fingers_notes', $clubbing_fingers_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':edema', $edema, PDO::PARAM_STR);
                    $phase2->bindParam(':cardio_fatigue', $cardio_fatigue, PDO::PARAM_STR);
                    $phase2->bindParam(':fatigue_notes', $fatigue_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':orthopnea', $orthopnea, PDO::PARAM_STR);
                    $phase2->bindParam(':orthopnea_notes', $orthopnea_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':palpitation', $palpitation, PDO::PARAM_STR);
                    $phase2->bindParam(':palpitation_notes', $palpitation_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':cardio_sweating', $cardio_sweating, PDO::PARAM_STR);
                    $phase2->bindParam(':sweating_notes', $sweating_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':syncope', $syncope, PDO::PARAM_STR);
                    $phase2->bindParam(':syncope_notes', $syncope_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':tachycardia', $tachycardia, PDO::PARAM_STR);
                    $phase2->bindParam(':tachycardia_notes', $tachycardia_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':cardio_others', $cardio_others, PDO::PARAM_STR);
                    $phase2->bindParam(':jaundiced', $jaundiced, PDO::PARAM_STR);
                    $phase2->bindParam(':jaundiced_notes', $jaundiced_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':pale', $pale, PDO::PARAM_STR);
                    $phase2->bindParam(':pale_notes', $pale_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':pink', $pink, PDO::PARAM_STR);
                    $phase2->bindParam(':pink_notes', $pink_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':purpura', $purpura, PDO::PARAM_STR);
                    $phase2->bindParam(':purpura_notes', $purpura_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':cyanosis', $cyanosis, PDO::PARAM_STR);
                    $phase2->bindParam(':cyanosis_notes', $cyanosis_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':above_three_seconds', $above_three_seconds, PDO::PARAM_STR);
                    $phase2->bindParam(':above_three_seconds_notes', $above_three_seconds_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':below_three_seconds', $below_three_seconds, PDO::PARAM_STR);
                    $phase2->bindParam(':below_three_seconds_notes', $below_three_seconds_notes, PDO::PARAM_STR);
                    $phase2->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
                    $phase2->execute();
                    //phase 2 end
                    //phase 3 start
                    $phase3_01 = $pdo4->prepare("INSERT IGNORE INTO `care_plan_01`(`sno`, `umr_no`, `ip_no`, `a1`, `a2`, `a3`, `a4`, `b1`, `b2`, `b3`, `b4`, `c1`, `c2`, `c3`, `c4`, `d1`, `d2`, `d3`, `d4`, `e1`, `e2`, `e3`, `e4`, `f1`, `f2`, `f3`, `f4`, `g1`, `g2`, `g3`, `g4`, `h1`, `h2`, `h3`, `h4`, `i1`, `i2`, `i3`, `i4`, `j1`, `j2`, `j3`, `j4`, `k1`, `k2`, `k3`, `k4`,`created_by`,`created_on`,`esatus`,`ip`) VALUES (NULL,:umr,:ipno,:a1,:a2,:a3,:a4,:b1,:b2,:b3,:b4,:c1,:c2,:c3,:c4,:d1,:d2,:d3,:d4,:e1,:e2,:e3,:e4,:f1,:f2,:f3,:f4,:g1,:g2,:g3,:g4,:h1,:h2,:h3,:h4,:i1,:i2,:i3,:i4,:j1,:j2,:j3,:j4,:k1,:k2,:k3,:k4,:userid,CURRENT_TIMESTAMP,'Active',:ip)");
                    $phase3_01->bindParam(':umr', $umr, PDO::PARAM_STR);
                    $phase3_01->bindParam(':ipno', $ipno, PDO::PARAM_STR);
                    $phase3_01->bindParam(':a1', $a1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':a2', $a2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':a3', $a3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':a4', $a4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':b1', $b1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':b2', $b2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':b3', $b3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':b4', $b4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':c1', $c1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':c2', $c2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':c3', $c3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':c4', $c4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':d1', $d1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':d2', $d2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':d3', $d3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':d4', $d4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':e1', $e1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':e2', $e2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':e3', $e3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':e4', $e4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':f1', $f1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':f2', $f2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':f3', $f3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':f4', $f4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':g1', $g1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':g2', $g2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':g3', $g3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':g4', $g4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':h1', $h1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':h2', $h2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':h3', $h3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':h4', $h4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':i1', $i1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':i2', $i2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':i3', $i3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':i4', $i4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':j1', $j1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':j2', $j2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':j3', $j3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':j4', $j4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':k1', $k1, PDO::PARAM_STR);
                    $phase3_01->bindParam(':k2', $k2, PDO::PARAM_STR);
                    $phase3_01->bindParam(':k3', $k3, PDO::PARAM_STR);
                    $phase3_01->bindParam(':k4', $k4, PDO::PARAM_STR);
                    $phase3_01->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
                    $phase3_01->bindParam(':ip', $ipaddress, PDO::PARAM_STR);
                    $phase3_01->execute();

                    //phase 3-2

                    $phase3_02 = $pdo4->prepare(" INSERT IGNORE INTO `care_plan_02`(`sno`, `umr_no`, `ip_num`, `l1`, `l2`, `l3`, `l4`, `m1`, `m2`, `m3`, `m4`, `n1`, `n2`, `n3`, `n4`, `o1`, `o2`, `o3`, `o4`, `p1`, `p2`, `p3`, `p4`, `q1`, `q2`, `q3`, `q4`, `r1`, `r2`, `r3`, `r4`, `s1`, `s2`, `s3`, `s4`, `t1`, `t2`, `t3`, `t4`, `u1`, `u2`, `u3`, `u4`, `v1`, `v2`, `v3`, `v4`,`created_by`,`created_on`,`estatus`,`ip`) VALUES (NULL,:umr_no,:ip_num,:l1,:l2,:l3,:l4,:m1,:m2,:m3,:m4,:n1,:n2,:n3,:n4,:o1,:o2,:o3,:o4,:p1,:p2,:p3,:p4,:q1,:q2,:q3,:q4,:r1,:r2,:r3,:r4,:s1,:s2,:s3,:s4,:t1,:t2,:t3,:t4,:u1,:u2,:u3,:u4,:v1,:v2,:v3,:v4,:userid,CURRENT_TIMESTAMP,'Active',:ip)");
                    $phase3_02->bindParam(':umr_no', $umr, PDO::PARAM_STR);
                    $phase3_02->bindParam(':ip_num', $ipno, PDO::PARAM_STR);
                    $phase3_02->bindParam(':l1', $l1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':l2', $l2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':l3', $l3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':l4', $l4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':m1', $m1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':m2', $m2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':m3', $m3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':m4', $m4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':n1', $n1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':n2', $n2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':n3', $n3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':n4', $n4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':o1', $o1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':o2', $o2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':o3', $o3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':o4', $o4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':p1', $p1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':p2', $p2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':p3', $p3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':p4', $p4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':q1', $q1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':q2', $q2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':q3', $q3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':q4', $q4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':r1', $r1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':r2', $r2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':r3', $r3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':r4', $r4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':s1', $s1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':s2', $s2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':s3', $s3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':s4', $s4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':t1', $t1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':t2', $t2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':t3', $t3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':t4', $t4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':u1', $u1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':u2', $u2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':u3', $u3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':u4', $u4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':v1', $v1, PDO::PARAM_STR);
                    $phase3_02->bindParam(':v2', $v2, PDO::PARAM_STR);
                    $phase3_02->bindParam(':v3', $v3, PDO::PARAM_STR);
                    $phase3_02->bindParam(':v4', $v4, PDO::PARAM_STR);
                    $phase3_02->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
                    $phase3_02->bindParam(':ip', $ipaddress, PDO::PARAM_STR);
                    $phase3_02->execute();


                    //phase 3 end
                    if ($ninsert->rowCount() > 0) {
                        $response['error'] = false;
                        $response['message'] = "Data Inserted";
                        $vitalsigns = $pdo4->prepare("INSERT IGNORE INTO `vital_signs_table`(`sno`, `page_id`, `assessment_type`, `admission_num`, `umr_no`, `captured_date_and_time`, `bp_position_sit`, `bp_type_sit`, `bp_systolic_sit`, `bp_diastolic_sit`, `bp_position_sleep`, `bp_type_sleep`, `bp_systolic_sleep`, `bp_diastolic_sleep`, `bp_position_stand`, `bp_type_stand`, `bp_systolic_stand`, `bp_diastolic_stand`, `bp_units`, `pulse_type`, `pulse_rate`, `pulse_units`, `heart_rate_type`, `heart_rate`, `heart_rate_units`, `respiratory_rate`, `respiratory_units`, `weight`, `weight_units`, `height_rate`, `height_units`, `bmi_rate`, `bmi_units`, `bsa_rate`, `bsa_units`, `temp_type`, `temp_rate`, `temp_units`, `spo2_type`, `spo2_type1`, `spo2_rate`, `pain_score`, `grbs`, `grbs_units`, `blood_group`, `created_on`, `created_by`, `modified_on`, `modified_by`, `estatus`) VALUES (NULL, :vital_sign_id, :atype, :ipno, :umr, :captured_date_and_time,'sit',:bp_dd_1,:bp_systolic_1,:bp_diastolic_1,'Sleep',:bp_dd_2,:bp_systolic_2,:bp_diastolic_2,'Stand',:bp_dd_3,:bp_systolic_3,:bp_diastolic_3,:bp_units,:pulse_dd,:pulse_rate,:pulse_units,:heart_rate_dd,:heart_rate,:heart_rate_units,:respiratory_rate,:respiratory_units,:weights,:weight_units,:height_rate,:height_units,:bmi_rate,:bmi_units,:bsa_rate,:bsa_units,:temp_dd,:temp_rate,:temp_units,:spo2_dd1,:spo2_dd2,:spo2_rate,:pain_score,:grbs,:grbs_units,:blood_group,CURRENT_TIMESTAMP,:userid,CURRENT_TIMESTAMP,:userid,'Active')");
                        $vitalsigns->bindParam(':vital_sign_id', $pgids, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':umr', $umr, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':ipno', $ipno, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':atype', $atype, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':captured_date_and_time', $captured_date_and_time, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_dd_1', $bp_dd_1, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_systolic_1', $bp_systolic_1, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_diastolic_1', $bp_diastolic_1, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_dd_2', $bp_dd_2, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_systolic_2', $bp_systolic_2, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_diastolic_2', $bp_diastolic_2, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_dd_3', $bp_dd_3, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_systolic_3', $bp_systolic_3, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_diastolic_3', $bp_diastolic_3, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bp_units', $bp_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':pulse_dd', $pulse_dd, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':pulse_rate', $pulse_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':pulse_units', $pulse_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':heart_rate_dd', $heart_rate_dd, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':heart_rate', $heart_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':heart_rate_units', $heart_rate_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':respiratory_rate', $respiratory_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':respiratory_units', $respiratory_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':weights', $weight, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':weight_units', $weight_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':height_rate', $height_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':height_units', $height_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bmi_rate', $bmi_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bmi_units', $bmi_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bsa_rate', $bsa_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':bsa_units', $bsa_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':temp_dd', $temp_dd, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':temp_rate', $temp_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':temp_units', $temp_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':spo2_dd1', $spo2_dd1, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':spo2_dd2', $spo2_dd2, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':spo2_rate', $spo2_rate, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':pain_score', $pain_score, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':grbs', $grbs, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':grbs_units', $grbs_units, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':blood_group', $blood_group, PDO::PARAM_STR);
                        $vitalsigns->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
                        $vitalsigns->execute();
                        if ($vitalsigns->rowCount() > 0) {
                            $response['error'] = false;
                            $response['message'] = "Data inserted";
                            //add to pain score
                            $psinsert = $pdo4->prepare("INSERT IGNORE INTO `pain_scores_table`(`sno`, `page_id`, `assessment_type`, `admission_num`,  `umr_no`, `doctor_uid`, `pain_type`, `pain_rate`, `doc_name`, `pain`, `pain_loc`, `pain_char`, `acute_chornic`, `pain_duration`, `dec_pain`, `inc_pain`, `action_plan`, `intervention`, `interventiond`, `heparin_therapy`, `createdby`, `createdon`, `modifiedby`, `modifiedon`, `status`) VALUES (NULL,:vital_sign_id, :atype, :admission_num, :umr, :nursingid, :pain_type, :pain_rate, :doc_name, :pain, :pain_loc, :pain_char, :acute_chornic, :pain_duration, :dec_pain, :inc_pain, :action_plan, :intervention, :interventiond, :heparin_therapy,:userid,CURRENT_TIMESTAMP,:userid,CURRENT_TIMESTAMP,'Active')");
                            $psinsert->bindParam(':admission_num', $ipno, PDO::PARAM_STR);
                            $psinsert->bindParam(':vital_sign_id', $pgids, PDO::PARAM_STR);
                            $psinsert->bindParam(':umr', $umr, PDO::PARAM_STR);
                            $psinsert->bindParam(':atype', $atype, PDO::PARAM_STR);
                            $psinsert->bindParam(':nursingid', $nursingid, PDO::PARAM_STR);
                            $psinsert->bindParam(':pain_type', $pain_scale_type, PDO::PARAM_STR);
                            $psinsert->bindParam(':pain_rate', $painscale_score, PDO::PARAM_STR);
                            $psinsert->bindParam(':doc_name', $doctor_name, PDO::PARAM_STR);
                            $psinsert->bindParam(':pain', $pain, PDO::PARAM_STR);
                            $psinsert->bindParam(':pain_loc', $pain_location, PDO::PARAM_STR);
                            $psinsert->bindParam(':pain_char', $pain_character, PDO::PARAM_STR);
                            $psinsert->bindParam(':acute_chornic', $pain_duration_type, PDO::PARAM_STR);
                            $psinsert->bindParam(':pain_duration', $pain_duration, PDO::PARAM_STR);
                            $psinsert->bindParam(':dec_pain', $factor_decreasing_pain, PDO::PARAM_STR);
                            $psinsert->bindParam(':inc_pain', $factor_increasing_pain, PDO::PARAM_STR);
                            $psinsert->bindParam(':action_plan', $action_plan, PDO::PARAM_STR);
                            $psinsert->bindParam(':intervention', $intervention, PDO::PARAM_STR);
                            $psinsert->bindParam(':interventiond', $intervention_therapy, PDO::PARAM_STR);
                            $psinsert->bindParam(':heparin_therapy', $heparin_therapy, PDO::PARAM_STR);
                            $psinsert->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
                            $psinsert->execute();
                            if ($psinsert->rowCount() > 0) {
                                //
                                $response['error'] = false;
                                $response['message'] = "Data inserted";
                            } else {
                                $response['error'] = true;
                                $response['message'] = "Sorry! Data not inserted in PS";
                            }
                        } else {
                            $response['error'] = true;
                            $response['message'] = "Sorry! Data not inserted in VS";
                        }
                    } else {
                        $response['error'] = true;
                        $response['message'] = "Sorry! Data not inserted";
                    }
                } else {
                    $response['error'] = true;
                    $response['message'] = "Nursing Id generation Failed";
                }
                // }             
            } else {
                $response["error"] = true;
                $response["message"] = "Patient Checked Out";
            }
        } else {
            $response['error'] = true;
            $response['message'] = "Access denied!";
        }
    } else {
        $response['error'] = true;
        $response['message'] = "Sorry! some details are missing";
    }
} catch (PDOException $e) {
    http_response_code(503);
    $response['error'] = true;
    $response['message'] = "Connection failed";
    $errorlog = $pdoread->prepare("INSERT IGNORE INTO `error_logs`(`sno`, `created_by`, `created_on`, `message`, `api_url`) VALUES (NULL,:userid,CURRENT_TIMESTAMP,:errmessage,:apiurl)");
    $errorlog->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
    $errorlog->bindParam(':errmessage', $e->getMessage(), PDO::PARAM_STR);
    $errorlog->bindParam(':apiurl', $apiurl, PDO::PARAM_STR);
    $errorlog->execute();
}

echo json_encode($response);
$pdoread = null;
$pdo4 = null;
?>