<?php 
header("Content-Type: application/json; charset=UTF-8");
header("Content-Security-Policy: default-src 'none';");
header("X-Frame-Options: SAMEORIGIN");
header("x-content-type-options: nosniff");
header("Referrer-Policy: same-origin");
header("Strict-Transport-Security: max-age=31536000;");
header("Permissions-Policy: geolocation=(self)");
header_remove('X-Powered-By');
include "pdo-db.php";
$data = json_decode(file_get_contents("php://input"));
$response = array();

//default params
$accesskey = trim($data->accesskey);
$ipno = $data->ipno;
$umr = $data->umr;
$atype = $data->atype;
$acat = $data->acat;
$aid = $data->aid;
$ptcategory = $data->ptcategory;
$total_score = $data->total_score;
$initiated_date_time = date("Y-m-d H:i:s", strtotime($data->initiated_date_time));
//default params
//vital params
$captured_date_and_time = ($data->captured_date_and_time);
$captured_date_and_time = str_replace("/", " ", $captured_date_and_time);
$admitted_status = $data->admitted_status;
$relation_name = $data->relation_name;
$relation_type = $data->relation_type;
$phone_number = trim($data->phone_number);
$other_relation_type = $data->other_relation_type;
$other_relation_name = $data->other_relation_name;
$other_phone_number = trim($data->other_phone_number);
$primary_language = $data->primary_language;
$education_type = $data->education_type;
$education_others = $data->education_others;
$reason_for_enquiry = $data->reason_for_enquiry;
$bp_check_position_1 = strtoupper($data->bp_check_position_1);
$bp_dd_1 = $data->bp_dd_1;
$bp_systolic_1 = $data->bp_systolic_1;
$bp_diastolic_1 = $data->bp_diastolic_1;
$bp_check_position_2 = strtoupper($data->bp_check_position_2);
$bp_dd_2 = $data->bp_dd_2;
$bp_systolic_2 = $data->bp_systolic_2;
$bp_diastolic_2 = $data->bp_diastolic_2;
$bp_check_position_3 = strtoupper($data->bp_check_position_3);
$bp_dd_3 = $data->bp_dd_3;
$bp_systolic_3 = $data->bp_systolic_3;
$bp_diastolic_3 = $data->bp_diastolic_3;
$bp_units = $data->bp_units;
$pulse_dd = $data->pulse_dd;
$pulse_rate = $data->pulse_rate;
$pulse_units = $data->pulse_units;
$heart_rate_dd = $data->heart_rate_dd;
$heart_rate = $data->heart_rate;
$heart_rate_units = $data->heart_rate_units;
$respiratory_rate = $data->respiratory_rate;
$respiratory_units = $data->respiratory_units;
$weight = $data->weight;
$weight_units = $data->weight_units;
$height_rate = $data->height_rate;
$height_units = $data->height_units;
$bmi_rate = $data->bmi_rate;
$bmi_units = $data->bmi_units;
$bsa_rate = $data->bsa_rate;
$bsa_units = $data->bsa_units;
$temp_dd = $data->temp_dd;
$temp_rate = $data->temp_rate;
$temp_units = $data->temp_units;
$spo2_dd1 = $data->spo2_dd1;
$spo2_dd2 = $data->spo2_dd2;
$spo2_rate = $data->spo2_rate;
$pain_score = $data->pain_score;
$grbs = $data->grbs;
$grbs_units = $data->grbs_units;
$blood_group = $data->blood_group;
$quest_1 = $data->quest_1;
$quest_1_response = $data->quest_1_response;
$quest_2 = $data->quest_2;
$quest_2_response = $data->quest_2_response;
$quest_3 = $data->quest_3;
$quest_3_response = $data->quest_3_response;
$dentures = $data->dentures;
$dentures_data = $data->dentures_data;
$hearing_aid = $data->hearing_aid;
$hearing_aid_data = $data->hearing_aid_data;
$eye_glasses = $data->eye_glasses;
$eye_glasses_data = $data->eye_glasses_data;
$contact_lens = $data->contact_lens;
$contact_lens_data = $data->contact_lens_data;
$valubles_type = $data->valubles_type;
$valubles = $data->valubles;
$valubles_data = $data->valubles_data;
$relation_for_patient = $data->relation_for_patient;
$handover_to = $data->handover_to;
$contact_number = $data->contact_number;
$activity = $data->activity;
$bathing = $data->bathing;
$eating = $data->eating;
$dressing = $data->dressing;
$toilet_use = $data->toilet_use;
$others = $data->others;
$orientation = $data->orientation;
$orientation_others = $data->orientation_others;
$allergies_medication = $data->allergies_medication;
$allergies_medication_data = $data->allergies_medication_data;
$food = $data->food;
$food_data = $data->food_data;
$other_allergies = $data->other_allergies;
$quest_4 = $data->quest_4;
$quest_4_response = $data->quest_4_response;
$quest_5 = $data->quest_5;
$quest_5_response = $data->quest_5_response;
$quest_6 = $data->quest_6;
$quest_6_response = $data->quest_6_response;
$quest_7 = $data->quest_7;
$quest_7_response = $data->quest_7_response;
$quest_8 = $data->quest_8;
$quest_8_response = $data->quest_8_response;
$quest_9 = $data->quest_9;
$quest_9_response = $data->quest_9_response;
$nursing_assessment = $data->nursing_assessment;
$goal = $data->goal;
$planning = $data->planning;
$implementation = $data->implementation;
$evaluation = $data->evaluation;
$pain_scale_type = $data->pain_scale_type;
$painscale_score = $data->painscale_score;
$doctor_name = $data->doctor_name;
$pain = $data->pain;
$pain_location = $data->pain_location;
$pain_character = $data->pain_character;
$pain_duration_type = $data->pain_duration_type;
$pain_duration = $data->pain_duration;
$factor_decreasing_pain = $data->factor_decreasing_pain;
$factor_increasing_pain = $data->factor_increasing_pain;
$action_plan = $data->action_plan;
$intervention = $data->intervention;
$intervention_therapy = $data->intervention_therapy;
$heparin_therapy = $data->heparin_therapy;
$quest_10 = $data->quest_10;
$quest_10_response = $data->quest_10_response;
$quest_11 = $data->quest_11;
$quest_11_response = $data->quest_11_response;
$quest_12 = $data->quest_12;
$quest_12_response = $data->quest_12_response;
$quest_13 = $data->quest_13;
$quest_13_response = $data->quest_13_response;
$quest_14 = $data->quest_14;
$quest_14_response = $data->quest_14_response;
$quest_15 = $data->quest_15;
$quest_15_response = $data->quest_15_response;
$behaviour_pain_1 = trim($data->behaviour_pain_1);
$behaviour_pain_2 = trim($data->behaviour_pain_2);
$behaviour_pain_3 = trim($data->behaviour_pain_3);
$behaviour_pain_score = trim($data->behaviour_pain_score);
$completed_status = trim($data->completed_status);
try {
	if (!empty($accesskey) && !empty($ipno) && !empty($umr)) {
		
		$check = $pdoread->prepare("SELECT `userid`,`cost_center` FROM `user_logins` WHERE `mobile_accesskey` = :accesskey AND `status` = 'Active'");
		$check->bindParam(':accesskey', $accesskey, PDO::PARAM_STR);
		$check->execute();
		$result = $check->fetch(PDO::FETCH_ASSOC);
		if ($check->rowCount() > 0) {
			if ($completed_statu != 'Completed') {
				//check if data exists already
				$ipcheck = $pdoread->prepare("SELECT `admission_num`, `created_on` AS cdate FROM `nursing_assessment_table` WHERE `admission_num`=:ipno AND `assessment_id`=:aid AND `cost_center`=:costcenter AND `is_active`='1' AND `completed_status`='Pending'");
				$ipcheck->bindParam(':ipno', $ipno, PDO::PARAM_STR);
				$ipcheck->bindParam(':aid', $aid, PDO::PARAM_STR);
				$ipcheck->bindParam(':costcenter', $result['cost_center'], PDO::PARAM_STR);
				$ipcheck->execute();
				$ipchecks = $ipcheck->fetch(PDO::FETCH_ASSOC);
				if ($ipcheck->rowCount() > 0) {
					if ($completed_status == 'Completed') {
						$completed_date = date('Y-m-d H:i:s');
					} else {
						$completed_date = '0000-00-00 00:00:00';
					}
					$update = $pdo4->prepare("UPDATE `nursing_assessment_table` SET `patient_category`=:ptcategory,`assessment_type`=:atype,`assessment_category`=:acat,`admitted_status`=:admitted_status,`relation_name`=:relation_name,`relation_type`=:relation_type,`phone_number`=:phone_number,`other_relation_name`=:other_relation_name,`other_relation_type`=:other_relation_type,`other_phone_number`=:other_phone_number,`primary_language`=:primary_language,`education_type`=:education_type,`education_others`=:education_others,`reason_for_enquiry`=:reason_for_enquiry,`captured_date_and_time`=:captured_date_and_time,`bp_check_position_1`=:bp_check_position_1,`bp_dd_1`=:bp_dd_1,`bp_systolic_1`=:bp_systolic_1,`bp_diastolic_1`=:bp_diastolic_1,`bp_check_position_2`=:bp_check_position_2,`bp_dd_2`=:bp_dd_2,`bp_systolic_2`=:bp_systolic_2,`bp_diastolic_2`=:bp_diastolic_2,`bp_check_position_3`=:bp_check_position_3,`bp_dd_3`=:bp_dd_3,`bp_systolic_3`=:bp_systolic_3,`bp_diastolic_3`=:bp_diastolic_3,`bp_units`=:bp_units,`pulse_dd`=:pulse_dd,`pulse_rate`=:pulse_rate,`pulse_units`=:pulse_units,`heart_rate_dd`=:heart_rate_dd,`heart_rate`=:heart_rate,`heart_rate_units`=:heart_rate_units,`respiratory_rate`=:respiratory_rate,`respiratory_units`=:respiratory_units,`weight`=:weight,`weight_units`=:weight_units,`height_rate`=:height_rate,`height_units`=:height_units,`bmi_rate`=:bmi_rate,`bmi_units`=:bmi_units,`bsa_rate`=:bsa_rate,`bsa_units`=:bsa_units,`temp_dd`=:temp_dd,`temp_rate`=:temp_rate,`temp_units`=:temp_units,`spo2_dd1`=:spo2_dd1,`spo2_dd2`=:spo2_dd2,`spo2_rate`=:spo2_rate,`pain_score`=:pain_score,`grbs`=:grbs,`grbs_units`=:grbs_units,`blood_group`=:blood_group,`quest_1`=:quest_1,`quest_1_response`=:quest_1_response,`quest_2`=:quest_2,`quest_2_response`=:quest_2_response,`quest_3`=:quest_3,`quest_3_response`=:quest_3_response,`dentures`=:dentures,`dentures_data`=:dentures_data,`hearing_aid`=:hearing_aid,`hearing_aid_data`=:hearing_aid_data,`eye_glasses`=:eye_glasses,`eye_glasses_data`=:eye_glasses_data,`contact_lens`=:contact_lens,`contact_lens_data`=:contact_lens_data,`valubles_type`=:valubles_type,`valubles`=:valubles,`valubles_data`=:valubles_data,`relation_for_patient`=:relation_for_patient,`handover_to`=:handover_to,`contact_number`=:contact_number,`activity`=:activity,`bathing`=:bathing,`eating`=:eating,`dressing`=:dressing,`toilet_use`=:toilet_use,`others`=:others,`orientation`=:orientation,`orientation_others`=:orientation_others,`allergies_medication`=:allergies_medication,`allergies_medication_data`=:allergies_medication_data,`food`=:food,`food_data`=:food_data,`other_allergies`=:other_allergies,`quest_4`=:quest_4,`quest_4_response`=:quest_4_response,`quest_5`=:quest_5,`quest_5_response`=:quest_5_response,`quest_6`=:quest_6,`quest_6_response`=:quest_6_response,`quest_7`=:quest_7,`quest_7_response`=:quest_7_response,`quest_8`=:quest_8,`quest_8_response`=:quest_8_response,`quest_9`=:quest_9,`quest_9_response`=:quest_9_response,`nursing_assessment`=:nursing_assessment,`goal`=:goal,`planning`=:planning,`implementation`=:implementation,`evaluation`=:evaluation,`pain_scale_type`=:pain_scale_type,`painscale_score`=:painscale_score,`doctor_name`=:doctor_name,`pain`=:pain,`pain_location`=:pain_location,`pain_character`=:pain_character,`pain_duration_type`=:pain_duration_type,`pain_duration`=:pain_duration,`factor_decreasing_pain`=:factor_decreasing_pain,`factor_increasing_pain`=:factor_increasing_pain,`action_plan`=:action_plan,`intervention`=:intervention,`intervention_therapy`=:intervention_therapy,`heparin_therapy`=:heparin_therapy,`behaviour_pain_1`=:behaviour_pain_1,`behaviour_pain_2`=:behaviour_pain_2,`behaviour_pain_3`=:behaviour_pain_3,`behaviour_pain_score`=:behaviour_pain_score,`quest_10`=:quest_10,`quest_10_response`=:quest_10_response,`quest_11`=:quest_11,`quest_11_response`=:quest_11_response,`quest_12`=:quest_12,`quest_12_response`=:quest_12_response,`quest_13`=:quest_13,`quest_13_response`=:quest_13_response,`quest_14`=:quest_14,`quest_14_response`=:quest_14_response,`quest_15`=:quest_15,`quest_15_response`=:quest_15_response,`total_score`=:total_score,`modified_on`=CURRENT_TIMESTAMP,`modified_by`=:userid,`cost_center`=:costcenter,`completed_status`=:completed_status,`completed_date`=CURRENT_TIMESTAMP WHERE `admission_num`=:ipno AND `assessment_id`=:aid AND `cost_center`=:costcenter AND `is_active`='1'");
					$update->bindParam(':ipno', $ipno, PDO::PARAM_STR);
					$update->bindParam(':ptcategory', $ptcategory, PDO::PARAM_STR);
					$update->bindParam(':atype', $atype, PDO::PARAM_STR);
					$update->bindParam(':aid', $aid, PDO::PARAM_STR);
					$update->bindParam(':acat', $acat, PDO::PARAM_STR);
					$update->bindParam(':admitted_status', $admitted_status, PDO::PARAM_STR);
					$update->bindParam(':relation_name', $relation_name, PDO::PARAM_STR);
					$update->bindParam(':relation_type', $relation_type, PDO::PARAM_STR);
					$update->bindParam(':phone_number', $phone_number, PDO::PARAM_STR);
					$update->bindParam(':other_relation_type', $other_relation_type, PDO::PARAM_STR);
					$update->bindParam(':other_relation_name', $other_relation_name, PDO::PARAM_STR);
					$update->bindParam(':other_phone_number', $other_phone_number, PDO::PARAM_STR);
					$update->bindParam(':primary_language', $primary_language, PDO::PARAM_STR);
					$update->bindParam(':education_type', $education_type, PDO::PARAM_STR);
					$update->bindParam(':education_others', $education_others, PDO::PARAM_STR);
					$update->bindParam(':reason_for_enquiry', $reason_for_enquiry, PDO::PARAM_STR);
					$update->bindParam(':captured_date_and_time', $captured_date_and_time, PDO::PARAM_STR);
					$update->bindParam(':bp_check_position_1', $bp_check_position_1, PDO::PARAM_STR);
					$update->bindParam(':bp_dd_1', $bp_dd_1, PDO::PARAM_STR);
					$update->bindParam(':bp_systolic_1', $bp_systolic_1, PDO::PARAM_STR);
					$update->bindParam(':bp_diastolic_1', $bp_diastolic_1, PDO::PARAM_STR);
					$update->bindParam(':bp_check_position_2', $bp_check_position_2, PDO::PARAM_STR);
					$update->bindParam(':bp_dd_2', $bp_dd_2, PDO::PARAM_STR);
					$update->bindParam(':bp_systolic_2', $bp_systolic_2, PDO::PARAM_STR);
					$update->bindParam(':bp_diastolic_2', $bp_diastolic_2, PDO::PARAM_STR);
					$update->bindParam(':bp_check_position_3', $bp_check_position_3, PDO::PARAM_STR);
					$update->bindParam(':bp_dd_3', $bp_dd_3, PDO::PARAM_STR);
					$update->bindParam(':bp_systolic_3', $bp_systolic_3, PDO::PARAM_STR);
					$update->bindParam(':bp_diastolic_3', $bp_diastolic_3, PDO::PARAM_STR);
					$update->bindParam(':bp_units', $bp_units, PDO::PARAM_STR);
					$update->bindParam(':pulse_dd', $pulse_dd, PDO::PARAM_STR);
					$update->bindParam(':pulse_rate', $pulse_rate, PDO::PARAM_STR);
					$update->bindParam(':pulse_units', $pulse_units, PDO::PARAM_STR);
					$update->bindParam(':heart_rate_dd', $heart_rate_dd, PDO::PARAM_STR);
					$update->bindParam(':heart_rate', $heart_rate, PDO::PARAM_STR);
					$update->bindParam(':heart_rate_units', $heart_rate_units, PDO::PARAM_STR);
					$update->bindParam(':respiratory_rate', $respiratory_rate, PDO::PARAM_STR);
					$update->bindParam(':respiratory_units', $respiratory_units, PDO::PARAM_STR);
					$update->bindParam(':weight', $weight, PDO::PARAM_STR);
					$update->bindParam(':weight_units', $weight_units, PDO::PARAM_STR);
					$update->bindParam(':height_rate', $height_rate, PDO::PARAM_STR);
					$update->bindParam(':height_units', $height_units, PDO::PARAM_STR);
					$update->bindParam(':bmi_rate', $bmi_rate, PDO::PARAM_STR);
					$update->bindParam(':bmi_units', $bmi_units, PDO::PARAM_STR);
					$update->bindParam(':bsa_rate', $bsa_rate, PDO::PARAM_STR);
					$update->bindParam(':bsa_units', $bsa_units, PDO::PARAM_STR);
					$update->bindParam(':temp_dd', $temp_dd, PDO::PARAM_STR);
					$update->bindParam(':temp_rate', $temp_rate, PDO::PARAM_STR);
					$update->bindParam(':temp_units', $temp_units, PDO::PARAM_STR);
					$update->bindParam(':spo2_dd1', $spo2_dd1, PDO::PARAM_STR);
					$update->bindParam(':spo2_dd2', $spo2_dd2, PDO::PARAM_STR);
					$update->bindParam(':spo2_rate', $spo2_rate, PDO::PARAM_STR);
					$update->bindParam(':pain_score', $pain_score, PDO::PARAM_STR);
					$update->bindParam(':grbs', $grbs, PDO::PARAM_STR);
					$update->bindParam(':grbs_units', $grbs_units, PDO::PARAM_STR);
					$update->bindParam(':blood_group', $blood_group, PDO::PARAM_STR);
					$update->bindParam(':quest_1', $quest_1, PDO::PARAM_STR);
					$update->bindParam(':quest_1_response', $quest_1_response, PDO::PARAM_STR);
					$update->bindParam(':quest_2', $quest_2, PDO::PARAM_STR);
					$update->bindParam(':quest_2_response', $quest_2_response, PDO::PARAM_STR);
					$update->bindParam(':quest_3', $quest_3, PDO::PARAM_STR);
					$update->bindParam(':quest_3_response', $quest_3_response, PDO::PARAM_STR);
					$update->bindParam(':dentures', $dentures, PDO::PARAM_STR);
					$update->bindParam(':dentures_data', $dentures_data, PDO::PARAM_STR);
					$update->bindParam(':hearing_aid', $hearing_aid, PDO::PARAM_STR);
					$update->bindParam(':hearing_aid_data', $hearing_aid_data, PDO::PARAM_STR);
					$update->bindParam(':eye_glasses', $eye_glasses, PDO::PARAM_STR);
					$update->bindParam(':eye_glasses_data', $eye_glasses_data, PDO::PARAM_STR);
					$update->bindParam(':contact_lens', $contact_lens, PDO::PARAM_STR);
					$update->bindParam(':contact_lens_data', $contact_lens_data, PDO::PARAM_STR);
					$update->bindParam(':valubles_type', $valubles_type, PDO::PARAM_STR);
					$update->bindParam(':valubles', $valubles, PDO::PARAM_STR);
					$update->bindParam(':valubles_data', $valubles_data, PDO::PARAM_STR);
					$update->bindParam(':relation_for_patient', $relation_for_patient, PDO::PARAM_STR);
					$update->bindParam(':handover_to', $handover_to, PDO::PARAM_STR);
					$update->bindParam(':contact_number', $contact_number, PDO::PARAM_STR);
					$update->bindParam(':activity', $activity, PDO::PARAM_STR);
					$update->bindParam(':bathing', $bathing, PDO::PARAM_STR);
					$update->bindParam(':eating', $eating, PDO::PARAM_STR);
					$update->bindParam(':dressing', $dressing, PDO::PARAM_STR);
					$update->bindParam(':toilet_use', $toilet_use, PDO::PARAM_STR);
					$update->bindParam(':others', $others, PDO::PARAM_STR);
					$update->bindParam(':orientation', $orientation, PDO::PARAM_STR);
					$update->bindParam(':orientation_others', $orientation_others, PDO::PARAM_STR);
					$update->bindParam(':allergies_medication', $allergies_medication, PDO::PARAM_STR);
					$update->bindParam(':allergies_medication_data', $allergies_medication_data, PDO::PARAM_STR);
					$update->bindParam(':food', $food, PDO::PARAM_STR);
					$update->bindParam(':food_data', $food_data, PDO::PARAM_STR);
					$update->bindParam(':other_allergies', $other_allergies, PDO::PARAM_STR);
					$update->bindParam(':quest_4', $quest_4, PDO::PARAM_STR);
					$update->bindParam(':quest_4_response', $quest_4_response, PDO::PARAM_STR);
					$update->bindParam(':quest_5', $quest_5, PDO::PARAM_STR);
					$update->bindParam(':quest_5_response', $quest_5_response, PDO::PARAM_STR);
					$update->bindParam(':quest_6', $quest_6, PDO::PARAM_STR);
					$update->bindParam(':quest_6_response', $quest_6_response, PDO::PARAM_STR);
					$update->bindParam(':quest_7', $quest_7, PDO::PARAM_STR);
					$update->bindParam(':quest_7_response', $quest_7_response, PDO::PARAM_STR);
					$update->bindParam(':quest_8', $quest_8, PDO::PARAM_STR);
					$update->bindParam(':quest_8_response', $quest_8_response, PDO::PARAM_STR);
					$update->bindParam(':quest_9', $quest_9, PDO::PARAM_STR);
					$update->bindParam(':quest_9_response', $quest_9_response, PDO::PARAM_STR);
					$update->bindParam(':nursing_assessment', $nursing_assessment, PDO::PARAM_STR);
					$update->bindParam(':goal', $goal, PDO::PARAM_STR);
					$update->bindParam(':planning', $planning, PDO::PARAM_STR);
					$update->bindParam(':implementation', $implementation, PDO::PARAM_STR);
					$update->bindParam(':evaluation', $evaluation, PDO::PARAM_STR);
					$update->bindParam(':pain_scale_type', $pain_scale_type, PDO::PARAM_STR);
					$update->bindParam(':painscale_score', $painscale_score, PDO::PARAM_STR);
					$update->bindParam(':doctor_name', $doctor_name, PDO::PARAM_STR);
					$update->bindParam(':pain', $pain, PDO::PARAM_STR);
					$update->bindParam(':pain_location', $pain_location, PDO::PARAM_STR);
					$update->bindParam(':pain_character', $pain_character, PDO::PARAM_STR);
					$update->bindParam(':pain_duration_type', $pain_duration_type, PDO::PARAM_STR);
					$update->bindParam(':pain_duration', $pain_duration, PDO::PARAM_STR);
					$update->bindParam(':factor_decreasing_pain', $factor_decreasing_pain, PDO::PARAM_STR);
					$update->bindParam(':factor_increasing_pain', $factor_increasing_pain, PDO::PARAM_STR);
					$update->bindParam(':action_plan', $action_plan, PDO::PARAM_STR);
					$update->bindParam(':intervention', $intervention, PDO::PARAM_STR);
					$update->bindParam(':intervention_therapy', $intervention_therapy, PDO::PARAM_STR);
					$update->bindParam(':heparin_therapy', $heparin_therapy, PDO::PARAM_STR);
					$update->bindParam(':quest_10', $quest_10, PDO::PARAM_STR);
					$update->bindParam(':quest_10_response', $quest_10_response, PDO::PARAM_STR);
					$update->bindParam(':quest_11', $quest_11, PDO::PARAM_STR);
					$update->bindParam(':quest_11_response', $quest_11_response, PDO::PARAM_STR);
					$update->bindParam(':quest_12', $quest_12, PDO::PARAM_STR);
					$update->bindParam(':quest_12_response', $quest_12_response, PDO::PARAM_STR);
					$update->bindParam(':quest_13', $quest_13, PDO::PARAM_STR);
					$update->bindParam(':quest_13_response', $quest_13_response, PDO::PARAM_STR);
					$update->bindParam(':quest_14', $quest_14, PDO::PARAM_STR);
					$update->bindParam(':quest_14_response', $quest_14_response, PDO::PARAM_STR);
					$update->bindParam(':quest_15', $quest_15, PDO::PARAM_STR);
					$update->bindParam(':quest_15_response', $quest_15_response, PDO::PARAM_STR);
					$update->bindParam(':behaviour_pain_1', $behaviour_pain_1, PDO::PARAM_STR);
					$update->bindParam(':behaviour_pain_2', $behaviour_pain_2, PDO::PARAM_STR);
					$update->bindParam(':behaviour_pain_3', $behaviour_pain_3, PDO::PARAM_STR);
					$update->bindParam(':behaviour_pain_score', $behaviour_pain_score, PDO::PARAM_STR);
					$update->bindParam(':total_score', $total_score, PDO::PARAM_STR);
					$update->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
					$update->bindParam(':costcenter', $result['cost_center'], PDO::PARAM_STR);
					$update->bindParam(':completed_date', $completed_date, PDO::PARAM_STR);
					$update->bindParam(':completed_status', $completed_status, PDO::PARAM_STR);
					$update->execute();
					if ($update->rowCount() > 0) {
						$response['error'] = false;
						$response['message'] = "Data Updated";
					} else {
						$response['error'] = true;
						$response['message'] = "Data Not Updated";
					}
				} else {

					$nid = $pdoread->prepare("SELECT IFNULL(MAX(`nursing_id`),CONCAT('NID',DATE_FORMAT(CURRENT_DATE,'%y%m'),'000000')) AS nursing_id FROM `nursing_assessment_table` WHERE `nursing_id` LIKE '%NID%' ");
					$nid->execute();
					if ($nid->rowCount() > 0) {
						$res = $nid->fetch(PDO::FETCH_ASSOC);
						$nursing = $res['nursing_id'];
						$nursingid = ++$nursing;
						//nursing id created
						//insert into the table
						$ninsert = $pdo4->prepare("INSERT IGNORE INTO `nursing_assessment_table`(`sno`, `admission_num`, `umr_no`, `nursing_id`, `patient_category`, `assessment_type`, `assessment_id`, `assessment_category`, `admitted_status`, `relation_name`, `relation_type`, `phone_number`, `other_relation_name`, `other_relation_type`, `other_phone_number`, `primary_language`, `education_type`, `education_others`, `reason_for_enquiry`, `captured_date_and_time`, `bp_check_position_1`, `bp_dd_1`, `bp_systolic_1`, `bp_diastolic_1`, `bp_check_position_2`, `bp_dd_2`, `bp_systolic_2`, `bp_diastolic_2`, `bp_check_position_3`, `bp_dd_3`, `bp_systolic_3`, `bp_diastolic_3`, `bp_units`, `pulse_dd`, `pulse_rate`, `pulse_units`, `heart_rate_dd`, `heart_rate`, `heart_rate_units`, `respiratory_rate`, `respiratory_units`, `weight`, `weight_units`, `height_rate`, `height_units`, `bmi_rate`, `bmi_units`, `bsa_rate`, `bsa_units`, `temp_dd`, `temp_rate`, `temp_units`, `spo2_dd1`, `spo2_dd2`, `spo2_rate`, `pain_score`, `grbs`, `grbs_units`, `blood_group`, `quest_1`, `quest_1_response`, `quest_2`, `quest_2_response`, `quest_3`, `quest_3_response`, `dentures`, `dentures_data`, `hearing_aid`, `hearing_aid_data`, `eye_glasses`, `eye_glasses_data`, `contact_lens`, `contact_lens_data`, `valubles_type`, `valubles`, `valubles_data`, `relation_for_patient`, `handover_to`, `contact_number`, `activity`, `bathing`, `eating`, `dressing`, `toilet_use`, `others`, `orientation`, `orientation_others`, `allergies_medication`, `allergies_medication_data`, `food`, `food_data`, `other_allergies`, `quest_4`, `quest_4_response`, `quest_5`, `quest_5_response`, `quest_6`, `quest_6_response`, `quest_7`, `quest_7_response`, `quest_8`, `quest_8_response`, `quest_9`, `quest_9_response`, `nursing_assessment`, `goal`, `planning`, `implementation`, `evaluation`, `pain_scale_type`, `painscale_score`, `doctor_name`, `pain`, `pain_location`, `pain_character`, `pain_duration_type`, `pain_duration`, `factor_decreasing_pain`, `factor_increasing_pain`, `action_plan`, `intervention`, `intervention_therapy`, `heparin_therapy`, `quest_10`, `quest_10_response`, `quest_11`, `quest_11_response`, `quest_12`, `quest_12_response`, `quest_13`, `quest_13_response`, `quest_14`, `quest_14_response`, `quest_15`, `quest_15_response`, `is_active`, `admission_status`, `created_on`, `created_by`, `modified_on`, `modified_by`, `cost_center`, `ip`,`behaviour_pain_1`,`behaviour_pain_2`,`behaviour_pain_3`,`behaviour_pain_score`,`total_score`, `completed_status`, `completed_date`) VALUES (NULL,:ipno,:umr,:nid,:ptcategory,:atype,:aid,:acat,:admitted_status,:relation_name,:relation_type,:phone_number,:other_relation_name, :other_relation_type,:other_phone_number,:primary_language,:education_type,:education_others,:reason_for_enquiry,:captured_date_and_time,:bp_check_position_1,:bp_dd_1,:bp_systolic_1,:bp_diastolic_1,:bp_check_position_2,:bp_dd_2,:bp_systolic_2,:bp_diastolic_2,:bp_check_position_3,:bp_dd_3,:bp_systolic_3,:bp_diastolic_3,:bp_units,:pulse_dd,:pulse_rate,:pulse_units, :heart_rate_dd,:heart_rate,:heart_rate_units,:respiratory_rate,:respiratory_units,:weight,:weight_units,:height_rate,:height_units,:bmi_rate,:bmi_units,:bsa_rate,:bsa_units,:temp_dd,:temp_rate,:temp_units,:spo2_dd1,:spo2_dd2,:spo2_rate,:pain_score,:grbs,:grbs_units,:blood_group,:quest_1,:quest_1_response,:quest_2,:quest_2_response,:quest_3,:quest_3_response,:dentures,:dentures_data,:hearing_aid,:hearing_aid_data,:eye_glasses,:eye_glasses_data,:contact_lens,:contact_lens_data,:valubles_type,:valubles,:valubles_data,:relation_for_patient,:handover_to,:contact_number,:activity,:bathing,:eating,:dressing,:toilet_use,:others,:orientation,:orientation_others,:allergies_medication,:allergies_medication_data,:food,:food_data,:other_allergies,:quest_4,:quest_4_response,:quest_5,:quest_5_response,:quest_6,:quest_6_response,:quest_7,:quest_7_response,:quest_8,:quest_8_response,:quest_9,:quest_9_response,:nursing_assessment,:goal,:planning,:implementation,:evaluation,:pain_scale_type,:painscale_score,:doctor_name,:pain,:pain_location,:pain_character,:pain_duration_type,:pain_duration,:factor_decreasing_pain,:factor_increasing_pain,:action_plan,:intervention,:intervention_therapy,:heparin_therapy,:quest_10,:quest_10_response,:quest_11,:quest_11_response,:quest_12,:quest_12_response,:quest_13,:quest_13_response,:quest_14,:quest_14_response,:quest_15,:quest_15_response,'1','Active',:initiated_date_time,:userid,'','',:costcenter,:ip,:behaviour_pain_1,:behaviour_pain_2,:behaviour_pain_3,:behaviour_pain_score,:total_score,'Pending', '') ");
						$ninsert->bindParam(':ipno', $ipno, PDO::PARAM_STR);
						$ninsert->bindParam(':umr', $umr, PDO::PARAM_STR);
						$ninsert->bindParam(':nid', $nursingid, PDO::PARAM_STR);
						$ninsert->bindParam(':ptcategory', $ptcategory, PDO::PARAM_STR);
						$ninsert->bindParam(':atype', $atype, PDO::PARAM_STR);
						$ninsert->bindParam(':aid', $aid, PDO::PARAM_STR);
						$ninsert->bindParam(':acat', $acat, PDO::PARAM_STR);
						$ninsert->bindParam(':admitted_status', $admitted_status, PDO::PARAM_STR);
						$ninsert->bindParam(':relation_name', $relation_name, PDO::PARAM_STR);
						$ninsert->bindParam(':relation_type', $relation_type, PDO::PARAM_STR);
						$ninsert->bindParam(':phone_number', $phone_number, PDO::PARAM_STR);
						$ninsert->bindParam(':other_relation_type', $other_relation_type, PDO::PARAM_STR);
						$ninsert->bindParam(':other_relation_name', $other_relation_name, PDO::PARAM_STR);
						$ninsert->bindParam(':other_phone_number', $other_phone_number, PDO::PARAM_STR);
						$ninsert->bindParam(':primary_language', $primary_language, PDO::PARAM_STR);
						$ninsert->bindParam(':education_type', $education_type, PDO::PARAM_STR);
						$ninsert->bindParam(':education_others', $education_others, PDO::PARAM_STR);
						$ninsert->bindParam(':reason_for_enquiry', $reason_for_enquiry, PDO::PARAM_STR);
						$ninsert->bindParam(':captured_date_and_time', $captured_date_and_time, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_check_position_1', $bp_check_position_1, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_dd_1', $bp_dd_1, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_systolic_1', $bp_systolic_1, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_diastolic_1', $bp_diastolic_1, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_check_position_2', $bp_check_position_2, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_dd_2', $bp_dd_2, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_systolic_2', $bp_systolic_2, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_diastolic_2', $bp_diastolic_2, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_check_position_3', $bp_check_position_3, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_dd_3', $bp_dd_3, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_systolic_3', $bp_systolic_3, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_diastolic_3', $bp_diastolic_3, PDO::PARAM_STR);
						$ninsert->bindParam(':bp_units', $bp_units, PDO::PARAM_STR);
						$ninsert->bindParam(':pulse_dd', $pulse_dd, PDO::PARAM_STR);
						$ninsert->bindParam(':pulse_rate', $pulse_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':pulse_units', $pulse_units, PDO::PARAM_STR);
						$ninsert->bindParam(':heart_rate_dd', $heart_rate_dd, PDO::PARAM_STR);
						$ninsert->bindParam(':heart_rate', $heart_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':heart_rate_units', $heart_rate_units, PDO::PARAM_STR);
						$ninsert->bindParam(':respiratory_rate', $respiratory_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':respiratory_units', $respiratory_units, PDO::PARAM_STR);
						$ninsert->bindParam(':weight', $weight, PDO::PARAM_STR);
						$ninsert->bindParam(':weight_units', $weight_units, PDO::PARAM_STR);
						$ninsert->bindParam(':height_rate', $height_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':height_units', $height_units, PDO::PARAM_STR);
						$ninsert->bindParam(':bmi_rate', $bmi_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':bmi_units', $bmi_units, PDO::PARAM_STR);
						$ninsert->bindParam(':bsa_rate', $bsa_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':bsa_units', $bsa_units, PDO::PARAM_STR);
						$ninsert->bindParam(':temp_dd', $temp_dd, PDO::PARAM_STR);
						$ninsert->bindParam(':temp_rate', $temp_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':temp_units', $temp_units, PDO::PARAM_STR);
						$ninsert->bindParam(':spo2_dd1', $spo2_dd1, PDO::PARAM_STR);
						$ninsert->bindParam(':spo2_dd2', $spo2_dd2, PDO::PARAM_STR);
						$ninsert->bindParam(':spo2_rate', $spo2_rate, PDO::PARAM_STR);
						$ninsert->bindParam(':pain_score', $pain_score, PDO::PARAM_STR);
						$ninsert->bindParam(':grbs', $grbs, PDO::PARAM_STR);
						$ninsert->bindParam(':grbs_units', $grbs_units, PDO::PARAM_STR);
						$ninsert->bindParam(':blood_group', $blood_group, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_1', $quest_1, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_1_response', $quest_1_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_2', $quest_2, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_2_response', $quest_2_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_3', $quest_3, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_3_response', $quest_3_response, PDO::PARAM_STR);
						$ninsert->bindParam(':dentures', $dentures, PDO::PARAM_STR);
						$ninsert->bindParam(':dentures_data', $dentures_data, PDO::PARAM_STR);
						$ninsert->bindParam(':hearing_aid', $hearing_aid, PDO::PARAM_STR);
						$ninsert->bindParam(':hearing_aid_data', $hearing_aid_data, PDO::PARAM_STR);
						$ninsert->bindParam(':eye_glasses', $eye_glasses, PDO::PARAM_STR);
						$ninsert->bindParam(':eye_glasses_data', $eye_glasses_data, PDO::PARAM_STR);
						$ninsert->bindParam(':contact_lens', $contact_lens, PDO::PARAM_STR);
						$ninsert->bindParam(':contact_lens_data', $contact_lens_data, PDO::PARAM_STR);
						$ninsert->bindParam(':valubles_type', $valubles_type, PDO::PARAM_STR);
						$ninsert->bindParam(':valubles', $valubles, PDO::PARAM_STR);
						$ninsert->bindParam(':valubles_data', $valubles_data, PDO::PARAM_STR);
						$ninsert->bindParam(':relation_for_patient', $relation_for_patient, PDO::PARAM_STR);
						$ninsert->bindParam(':handover_to', $handover_to, PDO::PARAM_STR);
						$ninsert->bindParam(':contact_number', $contact_number, PDO::PARAM_STR);
						$ninsert->bindParam(':activity', $activity, PDO::PARAM_STR);
						$ninsert->bindParam(':bathing', $bathing, PDO::PARAM_STR);
						$ninsert->bindParam(':eating', $eating, PDO::PARAM_STR);
						$ninsert->bindParam(':dressing', $dressing, PDO::PARAM_STR);
						$ninsert->bindParam(':toilet_use', $toilet_use, PDO::PARAM_STR);
						$ninsert->bindParam(':others', $others, PDO::PARAM_STR);
						$ninsert->bindParam(':orientation', $orientation, PDO::PARAM_STR);
						$ninsert->bindParam(':orientation_others', $orientation_others, PDO::PARAM_STR);
						$ninsert->bindParam(':allergies_medication', $allergies_medication, PDO::PARAM_STR);
						$ninsert->bindParam(':allergies_medication_data', $allergies_medication_data, PDO::PARAM_STR);
						$ninsert->bindParam(':food', $food, PDO::PARAM_STR);
						$ninsert->bindParam(':food_data', $food_data, PDO::PARAM_STR);
						$ninsert->bindParam(':other_allergies', $other_allergies, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_4', $quest_4, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_4_response', $quest_4_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_5', $quest_5, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_5_response', $quest_5_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_6', $quest_6, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_6_response', $quest_6_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_7', $quest_7, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_7_response', $quest_7_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_8', $quest_8, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_8_response', $quest_8_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_9', $quest_9, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_9_response', $quest_9_response, PDO::PARAM_STR);
						$ninsert->bindParam(':nursing_assessment', $nursing_assessment, PDO::PARAM_STR);
						$ninsert->bindParam(':goal', $goal, PDO::PARAM_STR);
						$ninsert->bindParam(':planning', $planning, PDO::PARAM_STR);
						$ninsert->bindParam(':implementation', $implementation, PDO::PARAM_STR);
						$ninsert->bindParam(':evaluation', $evaluation, PDO::PARAM_STR);
						$ninsert->bindParam(':pain_scale_type', $pain_scale_type, PDO::PARAM_STR);
						$ninsert->bindParam(':painscale_score', $painscale_score, PDO::PARAM_STR);
						$ninsert->bindParam(':doctor_name', $doctor_name, PDO::PARAM_STR);
						$ninsert->bindParam(':pain', $pain, PDO::PARAM_STR);
						$ninsert->bindParam(':pain_location', $pain_location, PDO::PARAM_STR);
						$ninsert->bindParam(':pain_character', $pain_character, PDO::PARAM_STR);
						$ninsert->bindParam(':pain_duration_type', $pain_duration_type, PDO::PARAM_STR);
						$ninsert->bindParam(':pain_duration', $pain_duration, PDO::PARAM_STR);
						$ninsert->bindParam(':factor_decreasing_pain', $factor_decreasing_pain, PDO::PARAM_STR);
						$ninsert->bindParam(':factor_increasing_pain', $factor_increasing_pain, PDO::PARAM_STR);
						$ninsert->bindParam(':action_plan', $action_plan, PDO::PARAM_STR);
						$ninsert->bindParam(':intervention', $intervention, PDO::PARAM_STR);
						$ninsert->bindParam(':intervention_therapy', $intervention_therapy, PDO::PARAM_STR);
						$ninsert->bindParam(':heparin_therapy', $heparin_therapy, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_10', $quest_10, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_10_response', $quest_10_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_11', $quest_11, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_11_response', $quest_11_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_12', $quest_12, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_12_response', $quest_12_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_13', $quest_13, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_13_response', $quest_13_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_14', $quest_14, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_14_response', $quest_14_response, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_15', $quest_15, PDO::PARAM_STR);
						$ninsert->bindParam(':quest_15_response', $quest_15_response, PDO::PARAM_STR);
						$ninsert->bindParam(':behaviour_pain_1', $behaviour_pain_1, PDO::PARAM_STR);
						$ninsert->bindParam(':behaviour_pain_2', $behaviour_pain_2, PDO::PARAM_STR);
						$ninsert->bindParam(':behaviour_pain_3', $behaviour_pain_3, PDO::PARAM_STR);
						$ninsert->bindParam(':behaviour_pain_score', $behaviour_pain_score, PDO::PARAM_STR);
						$ninsert->bindParam(':total_score', $total_score, PDO::PARAM_STR);
						$ninsert->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
						$ninsert->bindParam(':costcenter', $result['cost_center'], PDO::PARAM_STR);
						$ninsert->bindParam(':ip', $ipaddress, PDO::PARAM_STR);
						$ninsert->bindParam(':initiated_date_time', $initiated_date_time, PDO::PARAM_STR);
						$ninsert->execute();
						if ($ninsert->rowCount() > 0) {
							http_response_code(200);
							$response['error'] = false;
							$response['message'] = "Data Inserted";

							$vitalsigns = $pdo4->prepare("INSERT IGNORE INTO `vital_signs_table`(`sno`, `assessment_type`, `admission_num`, `captured_date_and_time`, `bp_position_sit`, `bp_type_sit`, `bp_systolic_sit`, `bp_diastolic_sit`, `bp_position_sleep`, `bp_type_sleep`, `bp_systolic_sleep`, `bp_diastolic_sleep`, `bp_position_stand`, `bp_type_stand`, `bp_systolic_stand`, `bp_diastolic_stand`, `bp_units`, `pulse_type`, `pulse_rate`, `pulse_units`, `heart_rate_type`, `heart_rate`, `heart_rate_units`, `respiratory_rate`, `respiratory_units`, `weight`, `weight_units`, `height_rate`, `height_units`, `bmi_rate`, `bmi_units`, `bsa_rate`, `bsa_units`, `temp_type`, `temp_rate`, `temp_units`, `spo2_type`, `spo2_type1`, `spo2_rate`, `pain_score`, `grbs`, `grbs_units`, `blood_group`, `created_on`, `created_by`, `modified_on`, `modified_by`, `estatus`) VALUES (NULL, :atype, :ipno,:captured_date_and_time,'sit',:bp_dd_1,:bp_systolic_1,:bp_diastolic_1,'Sleep',:bp_dd_2,:bp_systolic_2,:bp_diastolic_2,'Stand',:bp_dd_3,:bp_systolic_3,:bp_diastolic_3,:bp_units,:pulse_dd,:pulse_rate,:pulse_units,:heart_rate_dd,:heart_rate,:heart_rate_units,:respiratory_rate,:respiratory_units,:weights,:weight_units,:height_rate,:height_units,:bmi_rate,:bmi_units,:bsa_rate,:bsa_units,:temp_dd,:temp_rate,:temp_units,:spo2_dd1,:spo2_dd2,:spo2_rate,:pain_score,:grbs,:grbs_units,:blood_group,CURRENT_TIMESTAMP,:userid,CURRENT_TIMESTAMP,:userid,'Active')");
							$vitalsigns->bindParam(':ipno', $ipno, PDO::PARAM_STR);
							$vitalsigns->bindParam(':atype', $atype, PDO::PARAM_STR);
							$vitalsigns->bindParam(':captured_date_and_time', $captured_date_and_time, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_dd_1', $bp_dd_1, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_systolic_1', $bp_systolic_1, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_diastolic_1', $bp_diastolic_1, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_dd_2', $bp_dd_2, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_systolic_2', $bp_systolic_2, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_diastolic_2', $bp_diastolic_2, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_dd_3', $bp_dd_3, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_systolic_3', $bp_systolic_3, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_diastolic_3', $bp_diastolic_3, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bp_units', $bp_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':pulse_dd', $pulse_dd, PDO::PARAM_STR);
							$vitalsigns->bindParam(':pulse_rate', $pulse_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':pulse_units', $pulse_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':heart_rate_dd', $heart_rate_dd, PDO::PARAM_STR);
							$vitalsigns->bindParam(':heart_rate', $heart_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':heart_rate_units', $heart_rate_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':respiratory_rate', $respiratory_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':respiratory_units', $respiratory_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':weights', $weight, PDO::PARAM_STR);
							$vitalsigns->bindParam(':weight_units', $weight_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':height_rate', $height_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':height_units', $height_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bmi_rate', $bmi_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bmi_units', $bmi_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bsa_rate', $bsa_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':bsa_units', $bsa_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':temp_dd', $temp_dd, PDO::PARAM_STR);
							$vitalsigns->bindParam(':temp_rate', $temp_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':temp_units', $temp_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':spo2_dd1', $spo2_dd1, PDO::PARAM_STR);
							$vitalsigns->bindParam(':spo2_dd2', $spo2_dd2, PDO::PARAM_STR);
							$vitalsigns->bindParam(':spo2_rate', $spo2_rate, PDO::PARAM_STR);
							$vitalsigns->bindParam(':pain_score', $pain_score, PDO::PARAM_STR);
							$vitalsigns->bindParam(':grbs', $grbs, PDO::PARAM_STR);
							$vitalsigns->bindParam(':grbs_units', $grbs_units, PDO::PARAM_STR);
							$vitalsigns->bindParam(':blood_group', $blood_group, PDO::PARAM_STR);
							$vitalsigns->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
							$vitalsigns->execute();
						} else {
							http_response_code(503);
							$response['error'] = true;
							$response['message'] = "Sorry! Data Not Inserted";
						}
						//insertion done
					} else {
						http_response_code(503);
						$response['error'] = true;
						$response['message'] = "Nursing Id generation Failed";
					}
				}
			} else {
				http_response_code(503);
				$response['error'] = true;
				$response['message'] = "Cannot Be Authorized";
			}
		} else {
			http_response_code(400);
			$response['error'] = true;
			$response['message'] = "Access denied! Please try to re-login";
		}
	} else {
		http_response_code(400);
		$response['error'] = true;
		$response['message'] = "Sorry! some details are missing";
	}
} catch (PDOException $e) {
	http_response_code(503);
	$response['error'] = true;
	$response['message'] = "Connection failed" . $e->getMessage();
}
echo json_encode($response);
$pdo4 = null;
$pdoread = null;
?>