<?php
header("Content-Type: application/json; charset=UTF-8");
header("Content-Security-Policy: default-src 'none';");
header("X-Frame-Options: SAMEORIGIN");
header("x-content-type-options: nosniff");
header("Referrer-Policy: same-origin");
header("Strict-Transport-Security: max-age=31536000;");
header("Permissions-Policy: geolocation=(self)");
header_remove('X-Powered-By');
include "pdo-db.php";
$data = json_decode(file_get_contents("php://input"));
$accesskey = $data->accesskey;
$response = array();
$admission_num = trim($data->admission_num);
try {
     if(!empty($accesskey) && !empty($admission_num)){    
$check = $pdoread-> prepare("SELECT `userid`,`cost_center` FROM `user_logins` WHERE `mobile_accesskey` = :accesskey AND `status` = 'Active'");
$check->bindParam(':accesskey', $accesskey, PDO::PARAM_STR);
$check -> execute();
$result = $check->fetch(PDO::FETCH_ASSOC);
if($check -> rowCount() > 0){
$query=$pdoread->prepare("SELECT `admission_num`, `umr_no`, `nursingid`,`total_fall_risk`, `total_humpty`,  `ad_admission_mode`, `ad_admission_mode_other`, `ad_info_obtained_form`, `ad_info_obtained_form_other`, `ad_child_accompanied`, `ad_child_accompanied_other`, `ad_babies_head_circumference`, `ad_babies_birth_weight`, `ad_language_spoken`, `ad_language_spoken_other`, `ad_school_grade`, `ad_favorite_toy_hobbies`, `ad_vs_temperature`, `ad_vs_respiration`, `ad_vs_blood_pressur`, `ad_vs_pulse`, `ad_vs_spo2`, `ad_vs_Weight`, `ad_vs_height`, `ad_orientation_unit`, `ad_patient_right_responsibilities`, `ad_patient_right_responsibilities_other`, `ad_ve_brought_hospital`, `ad_ve_given_name`, `ad_ve_given_name_dtls`, `ad_ve_relation`, `ad_ve_relation_dtls`, `hh_health_problems`, `hh_health_problems_other`, `hh_health_problems_ifany_identified`, `hh_health_problems_ifany_identified_dtls`, `hh_health_problems_surgeries`, `hh_health_problems_surgeries_dtls`, `hh_health_problems_chickenpox`, DATE(`hh_health_problems_chickenpox_date`) as hh_health_problems_chickenpox_date, `hh_health_problems_tb`, DATE(`hh_health_problems_tb_date`)as hh_health_problems_tb_date, `hh_health_problems_pertussis`, DATE(`hh_health_problems_pertussis_date`) as hh_health_problems_pertussis_date, `hh_health_problems_meningitis`, DATE(`hh_health_problems_meningitis_date`) as hh_health_problems_meningitis_date, `hh_health_problems_influenza`, DATE(`hh_health_problems_influenza_date`) as hh_health_problems_influenza_date, `hh_health_problems_immunization_uptodate`, `hh_health_problems_immunization_unsure`, `hh_health_problems_immunization_no`, `hh_allergies`, `hh_allergies_dtls`, `hh_medication_history_disposition_med`, `hh_medication_history_disposition_med_home`, `hh_medication_history_disposition_med_dose_freq`, `hh_medication_history_last_dose`, `hh_sleep_rest`, `hh_psycho`, `hh_psycho_other`, `hh_psycho_living`, `hh_psycho_relationship`, `hh_psycho_phone`, `hh_psycho_people_living_with`, `hh_psycho_father_occup`, `hh_psycho_insurance`, `hh_religious`, `hh_religious_other`, `hh_religious_any_other`, `hh_religious_cul_practices`, `hh_religious_cul_practices_dtls`, `hh_gd_past_weights`, `hh_gd_past_heights`, `hh_gd_dm_socialsmile`, `hh_gd_dm_socialsmile_comments`, `hh_gd_dm_teething`, `hh_gd_dm_teething_comments`, `hh_gd_dm_unsupported`, `hh_gd_dm_unsupported_comments`, `hh_gd_dm_walked`, `hh_gd_dm_walked_comments`, `hh_gd_dm_usedwords`, `hh_gd_dm_usedwords_comments`, `hh_gd_dm_usedsentences`, `hh_gd_dm_usedsentences_comments`, `hh_gd_dm_toliettraining`, `hh_gd_dm_toliettraining_comments`, `hh_gd_dm_puberty`, `hh_gd_dm_puberty_comments`, `hh_pain_scale_used`, `hh_pain_patient_expresses`, `misc_nutrition_needs_res_feeding_breast_feeding`, `misc_nutrition_needs_res_feeding_breast_frequency`, `misc_nutrition_needs_res_feeding_breast_duration`, `misc_nutrition_needs_res_feeding_breast_na`, `misc_nutrition_needs_res_feeding_breast_solids`, `misc_nutrition_needs_res_feeding_bottle`, `misc_nutrition_needs_res_feeding_bottle_type`, `misc_nutrition_needs_res_feeding_bottle_amount`, `misc_nutrition_needs_res_feeding_bottle_frequency`, `misc_nutrition_needs_res_feeding_bottle_na`, `misc_nutrition_needs_res_feeding_tube`, `misc_nutrition_needs_res_feeding_tube_type`, `misc_nutrition_needs_res_feeding_tube_amount`, `misc_nutrition_needs_res_feeding_tube_frequency`, `misc_nutrition_needs_res_feeding_tube_na`, `misc_nutrition_needs_assistance_feeding`, `misc_nutrition_needs_appetite`, `misc_nutrition_needs_risk`, `misc_func_assmnt_cat_feeding_score`, `misc_func_assmnt_cat_feeding_other`, `misc_func_assmnt_cat_toileting_score`, `misc_func_assmnt_cat_toileting_other`, `misc_func_assmnt_cat_dressing_score`, `misc_func_assmnt_cat_dressing_other`, `misc_func_assmnt_cat_groomming_score`, `misc_func_assmnt_cat_groomming_other`, `misc_func_assmnt_cat_walking_score`, `misc_func_assmnt_cat_walking_other`, `misc_func_assmnt_cat_transfer_score`, `misc_func_assmnt_cat_transfer_other`, `misc_func_assmnt_cat_mobility_score`, `misc_func_assmnt_cat_mobility_other`, `misc_func_assmnt_cat_mobility_changes`, `misc_func_assmnt_cat_mobility_discribe`, `misc_educational_assmnt`, `misc_skin_risk_assmnt_sensory`, `misc_skin_risk_assmnt_sensory_dtls`, `misc_skin_risk_assmnt_moisture`,`misc_skin_risk_assmnt_moisture_dtls`, `misc_skin_risk_assmnt_activity`, `misc_skin_risk_assmnt_activity_dtls`, `misc_skin_risk_assmnt_mobility`, `misc_skin_risk_assmnt_mobility_dtls`, `misc_skin_risk_assmnt_nutrition`, `misc_skin_risk_assmnt_nutrition_dtls`, `misc_skin_risk_assmnt_friction`, `misc_skin_risk_assmnt_friction_dtls`, `misc_flacc_pain_assmnt_face`, `misc_humpty_dumpty_assmnt_age`, `misc_humpty_dumpty_assmnt_age_dtls`, `misc_humpty_dumpty_assmnt_gender`, `misc_humpty_dumpty_assmnt_gender_dtls`, `misc_humpty_dumpty_assmnt_diagnosis`, `misc_humpty_dumpty_assmnt_diagnosis_dtls`, `misc_humpty_dumpty_assmnt_cognitive`, `misc_humpty_dumpty_assmnt_congnitive_dtls`, `misc_humpty_dumpty_assmnt_envfactors`, `misc_humpty_dumpty_assmnt_envfactors_dtls`, `misc_humpty_dumpty_assmnt_surgery`, `misc_humpty_dumpty_assmnt_surgery_dtls`, `misc_humpty_dumpty_assmnt_medication`, `misc_humpty_dumpty_assmnt_medication_dtls`, `misc_nursing_assmnt`, `misc_nursing_diagnosis`, `misc_nursing_planning`, `misc_nursing_implementation`, `misc_nursing_evaluation`, `cost_center`, DATE_FORMAT(`modified_on`, '%d/%m/%Y %h:%i') as  modified_on, `modified_by`,`bmi_value` FROM `nursing_pediatric_init_assmnt_table` WHERE `admission_num` = :admission_num and `estatus` = 'Active'");
$query->bindParam(':admission_num',$admission_num,PDO::PARAM_STR);
$query->execute();
if($query->rowCount()>0){
	$response['error'] = false;
	$response['message']= "Data Found";
     while($res=$query->fetch(PDO::FETCH_ASSOC)){
     $response['admission_num']=$res['admission_num'];
$response['umr_no']=$res['umr_no'];
$response['bmi_value']=$res['bmi_value'];
$response['nursingid']=$res['nursingid'];
$response['total_fall_risk']=$res['total_fall_risk'];
$response['total_humpty']=$res['total_humpty'];
$response['ini_ass_ini_time']=$res['ini_ass_ini_time'];
$response['ini_ass_ini_date']=$res['ini_ass_ini_date'];
$response['phy_rec_time_ward']=$res['phy_rec_time_ward'];
$response['compl_time']=$res['compl_time'];
$response['delta_time']=$res['delta_time'];
$response['ad_admission_mode']=$res['ad_admission_mode'];
$response['ad_admission_mode_other']=$res['ad_admission_mode_other'];
$response['ad_info_obtained_form']=$res['ad_info_obtained_form'];
$response['ad_info_obtained_form_other']=$res['ad_info_obtained_form_other'];
$response['ad_child_accompanied']=$res['ad_child_accompanied'];
$response['ad_child_accompanied_other']=$res['ad_child_accompanied_other'];
$response['ad_babies_head_circumference']=$res['ad_babies_head_circumference'];
$response['ad_babies_birth_weight']=$res['ad_babies_birth_weight'];
$response['ad_language_spoken']=$res['ad_language_spoken'];
$response['ad_language_spoken_other']=$res['ad_language_spoken_other'];
$response['ad_school_grade']=$res['ad_school_grade'];
$response['ad_favorite_toy_hobbies']=$res['ad_favorite_toy_hobbies'];
$response['ad_vs_temperature']=$res['ad_vs_temperature'];
$response['ad_vs_respiration']=$res['ad_vs_respiration'];
$response['ad_vs_blood_pressur']=$res['ad_vs_blood_pressur'];
$response['ad_vs_pulse']=$res['ad_vs_pulse'];
$response['ad_vs_spo2']=$res['ad_vs_spo2'];
$response['ad_vs_Weight']=$res['ad_vs_Weight'];
$response['ad_vs_height']=$res['ad_vs_height'];
$response['ad_orientation_unit']=$res['ad_orientation_unit'];
$response['ad_patient_right_responsibilities']=$res['ad_patient_right_responsibilities'];
$response['ad_patient_right_responsibilities_other']=$res['ad_patient_right_responsibilities_other'];
$response['ad_ve_brought_hospital']=$res['ad_ve_brought_hospital'];
$response['ad_ve_given_name']=$res['ad_ve_given_name'];
$response['ad_ve_given_name_dtls']=$res['ad_ve_given_name_dtls'];
$response['ad_ve_relation']=$res['ad_ve_relation'];
$response['ad_ve_relation_dtls']=$res['ad_ve_relation_dtls'];
$response['hh_health_problems']=$res['hh_health_problems'];
$response['hh_health_problems_other']=$res['hh_health_problems_other'];
$response['hh_health_problems_ifany_identified']=$res['hh_health_problems_ifany_identified'];
$response['hh_health_problems_ifany_identified_dtls']=$res['hh_health_problems_ifany_identified_dtls'];
$response['hh_health_problems_surgeries']=$res['hh_health_problems_surgeries'];
$response['hh_health_problems_surgeries_dtls']=$res['hh_health_problems_surgeries_dtls'];
$response['hh_health_problems_chickenpox']=$res['hh_health_problems_chickenpox'];
$response['hh_health_problems_chickenpox_date']=$res['hh_health_problems_chickenpox_date'];
$response['hh_health_problems_tb']=$res['hh_health_problems_tb'];
$response['hh_health_problems_tb_date']=$res['hh_health_problems_tb_date'];
$response['hh_health_problems_pertussis']=$res['hh_health_problems_pertussis'];
$response['hh_health_problems_pertussis_date']=$res['hh_health_problems_pertussis_date'];
$response['hh_health_problems_meningitis']=$res['hh_health_problems_meningitis'];
$response['hh_health_problems_meningitis_date']=$res['hh_health_problems_meningitis_date'];
$response['hh_health_problems_influenza']=$res['hh_health_problems_influenza'];
$response['hh_health_problems_influenza_date']=$res['hh_health_problems_influenza_date'];
$response['hh_health_problems_immunization_uptodate']=$res['hh_health_problems_immunization_uptodate'];
$response['hh_health_problems_immunization_unsure']=$res['hh_health_problems_immunization_unsure'];
$response['hh_health_problems_immunization_no']=$res['hh_health_problems_immunization_no'];
$response['hh_allergies']=$res['hh_allergies'];
$response['hh_allergies_dtls']=$res['hh_allergies_dtls'];
$response['hh_medication_history_disposition_med']=$res['hh_medication_history_disposition_med'];
$response['hh_medication_history_disposition_med_home']=$res['hh_medication_history_disposition_med_home'];
$response['hh_medication_history_disposition_med_dose_freq']=$res['hh_medication_history_disposition_med_dose_freq'];
$response['hh_medication_history_last_dose']=$res['hh_medication_history_last_dose'];
$response['hh_sleep_rest']=$res['hh_sleep_rest'];
$response['hh_psycho']=$res['hh_psycho'];
$response['hh_psycho_other']=$res['hh_psycho_other'];
$response['hh_psycho_living']=$res['hh_psycho_living'];
$response['hh_psycho_relationship']=$res['hh_psycho_relationship'];
$response['hh_psycho_phone']=$res['hh_psycho_phone'];
$response['hh_psycho_people_living_with']=$res['hh_psycho_people_living_with'];
$response['hh_psycho_father_occup']=$res['hh_psycho_father_occup'];
$response['hh_psycho_insurance']=$res['hh_psycho_insurance'];
$response['hh_religious']=$res['hh_religious'];
$response['hh_religious_other']=$res['hh_religious_other'];
$response['hh_religious_any_other']=$res['hh_religious_any_other'];
$response['hh_religious_cul_practices']=$res['hh_religious_cul_practices'];
$response['hh_religious_cul_practices_dtls']=$res['hh_religious_cul_practices_dtls'];
$response['hh_gd_past_weights']=$res['hh_gd_past_weights'];
$response['hh_gd_past_heights']=$res['hh_gd_past_heights'];
$response['hh_gd_dm_socialsmile']=$res['hh_gd_dm_socialsmile'];
$response['hh_gd_dm_socialsmile_comments']=$res['hh_gd_dm_socialsmile_comments'];
$response['hh_gd_dm_teething']=$res['hh_gd_dm_teething'];
$response['hh_gd_dm_teething_comments']=$res['hh_gd_dm_teething_comments'];
$response['hh_gd_dm_unsupported']=$res['hh_gd_dm_unsupported'];
$response['hh_gd_dm_unsupported_comments']=$res['hh_gd_dm_unsupported_comments'];
$response['hh_gd_dm_walked']=$res['hh_gd_dm_walked'];
$response['hh_gd_dm_walked_comments']=$res['hh_gd_dm_walked_comments'];
$response['hh_gd_dm_usedwords']=$res['hh_gd_dm_usedwords'];
$response['hh_gd_dm_usedwords_comments']=$res['hh_gd_dm_usedwords_comments'];
$response['hh_gd_dm_usedsentences']=$res['hh_gd_dm_usedsentences'];
$response['hh_gd_dm_usedsentences_comments']=$res['hh_gd_dm_usedsentences_comments'];
$response['hh_gd_dm_toliettraining']=$res['hh_gd_dm_toliettraining'];
$response['hh_gd_dm_toliettraining_comments']=$res['hh_gd_dm_toliettraining_comments'];
$response['hh_gd_dm_puberty']=$res['hh_gd_dm_puberty'];
$response['hh_gd_dm_puberty_comments']=$res['hh_gd_dm_puberty_comments'];
$response['hh_pain_scale_used']=$res['hh_pain_scale_used'];
$response['hh_pain_patient_expresses']=$res['hh_pain_patient_expresses'];
$response['misc_nutrition_needs_res_feeding_breast_feeding']=$res['misc_nutrition_needs_res_feeding_breast_feeding'];
$response['misc_nutrition_needs_res_feeding_breast_frequency']=$res['misc_nutrition_needs_res_feeding_breast_frequency'];
$response['misc_nutrition_needs_res_feeding_breast_duration']=$res['misc_nutrition_needs_res_feeding_breast_duration'];
$response['misc_nutrition_needs_res_feeding_breast_na']=$res['misc_nutrition_needs_res_feeding_breast_na'];
$response['misc_nutrition_needs_res_feeding_breast_solids']=$res['misc_nutrition_needs_res_feeding_breast_solids'];
$response['misc_nutrition_needs_res_feeding_bottle']=$res['misc_nutrition_needs_res_feeding_bottle'];
$response['misc_nutrition_needs_res_feeding_bottle_type']=$res['misc_nutrition_needs_res_feeding_bottle_type'];
$response['misc_nutrition_needs_res_feeding_bottle_amount']=$res['misc_nutrition_needs_res_feeding_bottle_amount'];
$response['misc_nutrition_needs_res_feeding_bottle_frequency']=$res['misc_nutrition_needs_res_feeding_bottle_frequency'];
$response['misc_nutrition_needs_res_feeding_bottle_na']=$res['misc_nutrition_needs_res_feeding_bottle_na'];
$response['misc_nutrition_needs_res_feeding_tube']=$res['misc_nutrition_needs_res_feeding_tube'];
$response['misc_nutrition_needs_res_feeding_tube_type']=$res['misc_nutrition_needs_res_feeding_tube_type'];
$response['misc_nutrition_needs_res_feeding_tube_amount']=$res['misc_nutrition_needs_res_feeding_tube_amount'];
$response['misc_nutrition_needs_res_feeding_tube_frequency']=$res['misc_nutrition_needs_res_feeding_tube_frequency'];
$response['misc_nutrition_needs_res_feeding_tube_na']=$res['misc_nutrition_needs_res_feeding_tube_na'];
$response['misc_nutrition_needs_assistance_feeding']=$res['misc_nutrition_needs_assistance_feeding'];
$response['misc_nutrition_needs_appetite']=$res['misc_nutrition_needs_appetite'];
$response['misc_nutrition_needs_risk']=$res['misc_nutrition_needs_risk'];
$response['misc_func_assmnt_cat_feeding_score']=$res['misc_func_assmnt_cat_feeding_score'];
$response['misc_func_assmnt_cat_feeding_other']=$res['misc_func_assmnt_cat_feeding_other'];
$response['misc_func_assmnt_cat_toileting_score']=$res['misc_func_assmnt_cat_toileting_score'];
$response['misc_func_assmnt_cat_toileting_other']=$res['misc_func_assmnt_cat_toileting_other'];
$response['misc_func_assmnt_cat_dressing_score']=$res['misc_func_assmnt_cat_dressing_score'];
$response['misc_func_assmnt_cat_dressing_other']=$res['misc_func_assmnt_cat_dressing_other'];
$response['misc_func_assmnt_cat_groomming_score']=$res['misc_func_assmnt_cat_groomming_score'];
$response['misc_func_assmnt_cat_groomming_other']=$res['misc_func_assmnt_cat_groomming_other'];
$response['misc_func_assmnt_cat_walking_score']=$res['misc_func_assmnt_cat_walking_score'];
$response['misc_func_assmnt_cat_walking_other']=$res['misc_func_assmnt_cat_walking_other'];
$response['misc_func_assmnt_cat_transfer_score']=$res['misc_func_assmnt_cat_transfer_score'];
$response['misc_func_assmnt_cat_transfer_other']=$res['misc_func_assmnt_cat_transfer_other'];
$response['misc_func_assmnt_cat_mobility_score']=$res['misc_func_assmnt_cat_mobility_score'];
$response['misc_func_assmnt_cat_mobility_other']=$res['misc_func_assmnt_cat_mobility_other'];
$response['misc_func_assmnt_cat_mobility_changes']=$res['misc_func_assmnt_cat_mobility_changes'];
$response['misc_func_assmnt_cat_mobility_discribe']=$res['misc_func_assmnt_cat_mobility_discribe'];
$response['misc_educational_assmnt']=$res['misc_educational_assmnt'];
$response['misc_skin_risk_assmnt_sensory']=$res['misc_skin_risk_assmnt_sensory'];
$response['misc_skin_risk_assmnt_sensory_dtls']=$res['misc_skin_risk_assmnt_sensory_dtls'];
$response['misc_skin_risk_assmnt_moisture']=$res['misc_skin_risk_assmnt_moisture'];
$response['misc_skin_risk_assmnt_moisture_dtls']=$res['misc_skin_risk_assmnt_moisture_dtls'];
$response['misc_skin_risk_assmnt_activity']=$res['misc_skin_risk_assmnt_activity'];
$response['misc_skin_risk_assmnt_activity_dtls']=$res['misc_skin_risk_assmnt_activity_dtls'];
$response['misc_skin_risk_assmnt_mobility']=$res['misc_skin_risk_assmnt_mobility'];
$response['misc_skin_risk_assmnt_mobility_dtls']=$res['misc_skin_risk_assmnt_mobility_dtls'];
$response['misc_skin_risk_assmnt_nutrition']=$res['misc_skin_risk_assmnt_nutrition'];
$response['misc_skin_risk_assmnt_nutrition_dtls']=$res['misc_skin_risk_assmnt_nutrition_dtls'];
$response['misc_skin_risk_assmnt_friction']=$res['misc_skin_risk_assmnt_friction'];
$response['misc_skin_risk_assmnt_friction_dtls']=$res['misc_skin_risk_assmnt_friction_dtls'];
$response['misc_flacc_pain_assmnt_face']=$res['misc_flacc_pain_assmnt_face'];
$response['misc_humpty_dumpty_assmnt_age']=$res['misc_humpty_dumpty_assmnt_age'];
$response['misc_humpty_dumpty_assmnt_age_dtls']=$res['misc_humpty_dumpty_assmnt_age_dtls'];
$response['misc_humpty_dumpty_assmnt_gender']=$res['misc_humpty_dumpty_assmnt_gender'];
$response['misc_humpty_dumpty_assmnt_gender_dtls']=$res['misc_humpty_dumpty_assmnt_gender_dtls'];
$response['misc_humpty_dumpty_assmnt_diagnosis']=$res['misc_humpty_dumpty_assmnt_diagnosis'];
$response['misc_humpty_dumpty_assmnt_diagnosis_dtls']=$res['misc_humpty_dumpty_assmnt_diagnosis_dtls'];
$response['misc_humpty_dumpty_assmnt_cognitive']=$res['misc_humpty_dumpty_assmnt_cognitive'];
$response['misc_humpty_dumpty_assmnt_congnitive_dtls']=$res['misc_humpty_dumpty_assmnt_congnitive_dtls'];
$response['misc_humpty_dumpty_assmnt_envfactors']=$res['misc_humpty_dumpty_assmnt_envfactors'];
$response['misc_humpty_dumpty_assmnt_envfactors_dtls']=$res['misc_humpty_dumpty_assmnt_envfactors_dtls'];
$response['misc_humpty_dumpty_assmnt_surgery']=$res['misc_humpty_dumpty_assmnt_surgery'];
$response['misc_humpty_dumpty_assmnt_surgery_dtls']=$res['misc_humpty_dumpty_assmnt_surgery_dtls'];
$response['misc_humpty_dumpty_assmnt_medication']=$res['misc_humpty_dumpty_assmnt_medication'];
$response['misc_humpty_dumpty_assmnt_medication_dtls']=$res['misc_humpty_dumpty_assmnt_medication_dtls'];
$response['misc_nursing_assmnt']=$res['misc_nursing_assmnt'];
$response['misc_nursing_diagnosis']=$res['misc_nursing_diagnosis'];
$response['misc_nursing_planning']=$res['misc_nursing_planning'];
$response['misc_nursing_implementation']=$res['misc_nursing_implementation'];
$response['misc_nursing_evaluation']=$res['misc_nursing_evaluation'];
$response['cost_center']=$res['cost_center'];
$response['modified_on']=$res['modified_on'];
$response['modified_by']=$res['modified_by'];
$response['compl_date']=$res['compl_date'];
$response['compl_time']=$res['compl_time'];
$response['phy_rec_time']=$res['phy_rec_time'];
$response['phy_rec_date']=$res['phy_rec_date'];
// $response['modified_by']=$res['modified_by'];
     } 
}else{
	$response['error'] = true;
	$response['message']= "No Data Found";
}
}else {	
     $response['error'] = true;
	$response['message']= "Access Denied";
}	
}else {	
     $response['error'] = true;
	$response['message']= "Sorry! some details are missing";
}
} catch(PDOException $e) {
	http_response_code(503);
	$response['error'] = true;
	$response['message']= "Connection failed".$e->getMessage();
}
echo json_encode($response);
$pdoread= null;
?>