<?php
header("Content-Type: application/json; charset=UTF-8");
header("Content-Security-Policy: default-src 'none';");
header("X-Frame-Options: SAMEORIGIN");
header("x-content-type-options: nosniff");
header("Referrer-Policy: same-origin");
header("Strict-Transport-Security: max-age=31536000;");
header("Permissions-Policy: geolocation=(self)");
header_remove('X-Powered-By');
include "pdo-db.php";
$data = json_decode(file_get_contents("php://input"));
$accesskey = $data->accesskey;
$response = array();
$admission_num = trim($data->admission_num);
$bmi_value = trim($data->bmi_value);
$umr_no = trim($data-> umr_no);
$total_fall_risk = ($data-> total_fall_risk);
$total_humpty = ($data-> total_humpty);
$phy_rec_time_ward = ($data-> phy_rec_time_ward);
$compl_time = ($data-> compl_time);
$delta_time = ($data-> delta_time);
$ad_admission_mode = trim($data-> ad_admission_mode);
$ad_admission_mode_other = trim($data-> ad_admission_mode_other);
$ad_info_obtained_form = trim($data-> ad_info_obtained_form);
$ad_info_obtained_form_other = trim($data-> ad_info_obtained_form_other);
$ad_child_accompanied = trim($data-> ad_child_accompanied);
$ad_child_accompanied_other = trim($data-> ad_child_accompanied_other);
$ad_babies_head_circumference = trim($data-> ad_babies_head_circumference);
$ad_babies_birth_weight = trim($data-> ad_babies_birth_weight);
$ad_language_spoken = trim($data-> ad_language_spoken);
$ad_language_spoken_other = trim($data-> ad_language_spoken_other);
$ad_school_grade = trim($data-> ad_school_grade);
$ad_favorite_toy_hobbies = trim($data-> ad_favorite_toy_hobbies);
$ad_vs_temperature = trim($data-> ad_vs_temperature);
$ad_vs_respiration = trim($data-> ad_vs_respiration);
$ad_vs_blood_pressur = trim($data-> ad_vs_blood_pressur);
$ad_vs_pulse = trim($data-> ad_vs_pulse);
$ad_vs_spo2 = trim($data-> ad_vs_spo2);
$ad_vs_Weight = trim($data-> ad_vs_Weight);
$ad_vs_height = trim($data-> ad_vs_height);
$ad_orientation_unit = trim($data-> ad_orientation_unit);
$ad_patient_right_responsibilities = trim($data-> ad_patient_right_responsibilities);
$ad_patient_right_responsibilities_other = trim($data-> ad_patient_right_responsibilities_other);
$ad_ve_brought_hospital = trim($data-> ad_ve_brought_hospital);
$ad_ve_given_name = trim($data-> ad_ve_given_name);
$ad_ve_given_name_dtls = trim($data-> ad_ve_given_name_dtls);
$ad_ve_relation = trim($data-> ad_ve_relation);
$ad_ve_relation_dtls = trim($data-> ad_ve_relation_dtls);
$hh_health_problems = trim($data-> hh_health_problems);
$hh_health_problems_other = trim($data-> hh_health_problems_other);
$hh_health_problems_ifany_identified = trim($data-> hh_health_problems_ifany_identified);
$hh_health_problems_ifany_identified_dtls = trim($data-> hh_health_problems_ifany_identified_dtls);
$hh_health_problems_surgeries = trim($data-> hh_health_problems_surgeries);
$hh_health_problems_surgeries_dtls = trim($data-> hh_health_problems_surgeries_dtls);
$hh_health_problems_chickenpox = trim($data-> hh_health_problems_chickenpox);
$hh_health_problems_chickenpox_date = trim($data-> hh_health_problems_chickenpox_date);
$hh_health_problems_tb = trim($data-> hh_health_problems_tb);
$hh_health_problems_tb_date = trim($data-> hh_health_problems_tb_date);
$hh_health_problems_pertussis = trim($data-> hh_health_problems_pertussis);
$hh_health_problems_pertussis_date = trim($data-> hh_health_problems_pertussis_date);
$hh_health_problems_meningitis = trim($data-> hh_health_problems_meningitis);
$hh_health_problems_meningitis_date = trim($data-> hh_health_problems_meningitis_date);
$hh_health_problems_influenza = trim($data-> hh_health_problems_influenza);
$hh_health_problems_influenza_date = trim($data-> hh_health_problems_influenza_date);
$hh_health_problems_immunization_uptodate = trim($data-> hh_health_problems_immunization_uptodate);
$hh_health_problems_immunization_unsure = trim($data-> hh_health_problems_immunization_unsure);
$hh_health_problems_immunization_no = trim($data-> hh_health_problems_immunization_no);
$hh_allergies = trim($data-> hh_allergies);
$hh_allergies_dtls = trim($data-> hh_allergies_dtls);
$hh_medication_history_disposition_med = trim($data-> hh_medication_history_disposition_med);
$hh_medication_history_disposition_med_home = trim($data-> hh_medication_history_disposition_med_home);
$hh_medication_history_disposition_med_dose_freq = trim($data-> hh_medication_history_disposition_med_dose_freq);
$hh_medication_history_last_dose = trim($data-> hh_medication_history_last_dose);
$hh_sleep_rest = trim($data-> hh_sleep_rest);
$hh_psycho = trim($data-> hh_psycho);
$hh_psycho_other = trim($data-> hh_psycho_other);
$hh_psycho_living = trim($data-> hh_psycho_living);
$hh_psycho_relationship = trim($data-> hh_psycho_relationship);
$hh_psycho_phone = trim($data-> hh_psycho_phone);
$hh_psycho_people_living_with = trim($data-> hh_psycho_people_living_with);
$hh_psycho_father_occup = trim($data-> hh_psycho_father_occup);
$hh_psycho_insurance = trim($data-> hh_psycho_insurance);
$hh_religious = trim($data-> hh_religious);
$hh_religious_other = trim($data-> hh_religious_other);
$hh_religious_any_other = trim($data-> hh_religious_any_other);
$hh_religious_cul_practices = trim($data-> hh_religious_cul_practices);
$hh_religious_cul_practices_dtls = trim($data-> hh_religious_cul_practices_dtls);
$hh_gd_past_weights = trim($data-> hh_gd_past_weights);
$hh_gd_past_heights = trim($data-> hh_gd_past_heights);
$hh_gd_dm_socialsmile = trim($data-> hh_gd_dm_socialsmile);
$hh_gd_dm_socialsmile_comments = trim($data-> hh_gd_dm_socialsmile_comments);
$hh_gd_dm_teething = trim($data-> hh_gd_dm_teething);
$hh_gd_dm_teething_comments = trim($data-> hh_gd_dm_teething_comments);
$hh_gd_dm_unsupported = trim($data-> hh_gd_dm_unsupported);
$hh_gd_dm_unsupported_comments = trim($data-> hh_gd_dm_unsupported_comments);
$hh_gd_dm_walked = trim($data-> hh_gd_dm_walked);
$hh_gd_dm_walked_comments = trim($data-> hh_gd_dm_walked_comments);
$hh_gd_dm_usedwords = trim($data-> hh_gd_dm_usedwords);
$hh_gd_dm_usedwords_comments = trim($data-> hh_gd_dm_usedwords_comments);
$hh_gd_dm_usedsentences = trim($data-> hh_gd_dm_usedsentences);
$hh_gd_dm_usedsentences_comments = trim($data-> hh_gd_dm_usedsentences_comments);
$hh_gd_dm_toliettraining = trim($data-> hh_gd_dm_toliettraining);
$hh_gd_dm_toliettraining_comments = trim($data-> hh_gd_dm_toliettraining_comments);
$hh_gd_dm_puberty = trim($data-> hh_gd_dm_puberty);
$hh_gd_dm_puberty_comments = trim($data-> hh_gd_dm_puberty_comments);
$hh_pain_scale_used = trim($data-> hh_pain_scale_used);
$hh_pain_patient_expresses = trim($data-> hh_pain_patient_expresses);
$misc_nutrition_needs_res_feeding_breast_feeding = trim($data-> misc_nutrition_needs_res_feeding_breast_feeding);
$misc_nutrition_needs_res_feeding_breast_frequency = trim($data-> misc_nutrition_needs_res_feeding_breast_frequency);
$misc_nutrition_needs_res_feeding_breast_duration = trim($data-> misc_nutrition_needs_res_feeding_breast_duration);
$misc_nutrition_needs_res_feeding_breast_na = trim($data-> misc_nutrition_needs_res_feeding_breast_na);
$misc_nutrition_needs_res_feeding_breast_solids = trim($data-> misc_nutrition_needs_res_feeding_breast_solids);
$misc_nutrition_needs_res_feeding_bottle = trim($data-> misc_nutrition_needs_res_feeding_bottle);
$misc_nutrition_needs_res_feeding_bottle_type = trim($data-> misc_nutrition_needs_res_feeding_bottle_type);
$misc_nutrition_needs_res_feeding_bottle_amount = trim($data-> misc_nutrition_needs_res_feeding_bottle_amount);
$misc_nutrition_needs_res_feeding_bottle_frequency = trim($data-> misc_nutrition_needs_res_feeding_bottle_frequency);
$misc_nutrition_needs_res_feeding_bottle_na = trim($data-> misc_nutrition_needs_res_feeding_bottle_na);
$misc_nutrition_needs_res_feeding_tube = trim($data-> misc_nutrition_needs_res_feeding_tube);
$misc_nutrition_needs_res_feeding_tube_type = trim($data-> misc_nutrition_needs_res_feeding_tube_type);
$misc_nutrition_needs_res_feeding_tube_amount = trim($data-> misc_nutrition_needs_res_feeding_tube_amount);
$misc_nutrition_needs_res_feeding_tube_frequency = trim($data-> misc_nutrition_needs_res_feeding_tube_frequency);
$misc_nutrition_needs_res_feeding_tube_na = trim($data-> misc_nutrition_needs_res_feeding_tube_na);
$misc_nutrition_needs_assistance_feeding = trim($data-> misc_nutrition_needs_assistance_feeding);
$misc_nutrition_needs_appetite = trim($data-> misc_nutrition_needs_appetite);
$misc_nutrition_needs_risk = trim($data-> misc_nutrition_needs_risk);
$misc_func_assmnt_cat_feeding_score = trim($data-> misc_func_assmnt_cat_feeding_score);
$misc_func_assmnt_cat_feeding_other = trim($data-> misc_func_assmnt_cat_feeding_other);
$misc_func_assmnt_cat_toileting_score = trim($data-> misc_func_assmnt_cat_toileting_score);
$misc_func_assmnt_cat_toileting_other = trim($data-> misc_func_assmnt_cat_toileting_other);
$misc_func_assmnt_cat_dressing_score = trim($data-> misc_func_assmnt_cat_dressing_score);
$misc_func_assmnt_cat_dressing_other = trim($data-> misc_func_assmnt_cat_dressing_other);
$misc_func_assmnt_cat_groomming_score = trim($data-> misc_func_assmnt_cat_groomming_score);
$misc_func_assmnt_cat_groomming_other = trim($data-> misc_func_assmnt_cat_groomming_other);
$misc_func_assmnt_cat_walking_score = trim($data-> misc_func_assmnt_cat_walking_score);
$misc_func_assmnt_cat_walking_other = trim($data-> misc_func_assmnt_cat_walking_other);
$misc_func_assmnt_cat_transfer_score = trim($data-> misc_func_assmnt_cat_transfer_score);
$misc_func_assmnt_cat_transfer_other = trim($data-> misc_func_assmnt_cat_transfer_other);
$misc_func_assmnt_cat_mobility_score = trim($data-> misc_func_assmnt_cat_mobility_score);
$misc_func_assmnt_cat_mobility_other = trim($data-> misc_func_assmnt_cat_mobility_other);
$misc_func_assmnt_cat_mobility_changes = trim($data-> misc_func_assmnt_cat_mobility_changes);
$misc_func_assmnt_cat_mobility_discribe = trim($data-> misc_func_assmnt_cat_mobility_discribe);
$misc_educational_assmnt = trim($data-> misc_educational_assmnt);
$misc_skin_risk_assmnt_sensory = trim($data-> misc_skin_risk_assmnt_sensory);
$misc_skin_risk_assmnt_sensory_dtls = trim($data-> misc_skin_risk_assmnt_sensory_dtls);
$misc_skin_risk_assmnt_moisture = trim($data-> misc_skin_risk_assmnt_moisture);
$misc_skin_risk_assmnt_moisture_dtls = trim($data-> misc_skin_risk_assmnt_moisture_dtls);
$misc_skin_risk_assmnt_activity = trim($data-> misc_skin_risk_assmnt_activity);
$misc_skin_risk_assmnt_activity_dtls = trim($data-> misc_skin_risk_assmnt_activity_dtls);
$misc_skin_risk_assmnt_mobility = trim($data-> misc_skin_risk_assmnt_mobility);
$misc_skin_risk_assmnt_mobility_dtls = trim($data-> misc_skin_risk_assmnt_mobility_dtls);
$misc_skin_risk_assmnt_nutrition = trim($data-> misc_skin_risk_assmnt_nutrition);
$misc_skin_risk_assmnt_nutrition_dtls = trim($data-> misc_skin_risk_assmnt_nutrition_dtls);
$misc_skin_risk_assmnt_friction = trim($data-> misc_skin_risk_assmnt_friction);
$misc_skin_risk_assmnt_friction_dtls = trim($data-> misc_skin_risk_assmnt_friction_dtls);
$misc_flacc_pain_assmnt_face = trim($data-> misc_flacc_pain_assmnt_face);
$misc_humpty_dumpty_assmnt_age = trim($data-> misc_humpty_dumpty_assmnt_age);
$misc_humpty_dumpty_assmnt_age_dtls = trim($data-> misc_humpty_dumpty_assmnt_age_dtls);
$misc_humpty_dumpty_assmnt_gender = trim($data-> misc_humpty_dumpty_assmnt_gender);
$misc_humpty_dumpty_assmnt_gender_dtls = trim($data-> misc_humpty_dumpty_assmnt_gender_dtls);
$misc_humpty_dumpty_assmnt_diagnosis = trim($data-> misc_humpty_dumpty_assmnt_diagnosis);
$misc_humpty_dumpty_assmnt_diagnosis_dtls = trim($data-> misc_humpty_dumpty_assmnt_diagnosis_dtls);
$misc_humpty_dumpty_assmnt_cognitive = trim($data-> misc_humpty_dumpty_assmnt_cognitive);
$misc_humpty_dumpty_assmnt_congnitive_dtls = trim($data-> misc_humpty_dumpty_assmnt_congnitive_dtls);
$misc_humpty_dumpty_assmnt_envfactors = trim($data-> misc_humpty_dumpty_assmnt_envfactors);
$misc_humpty_dumpty_assmnt_envfactors_dtls = trim($data-> misc_humpty_dumpty_assmnt_envfactors_dtls);
$misc_humpty_dumpty_assmnt_surgery = trim($data-> misc_humpty_dumpty_assmnt_surgery);
$misc_humpty_dumpty_assmnt_surgery_dtls = trim($data-> misc_humpty_dumpty_assmnt_surgery_dtls);
$misc_humpty_dumpty_assmnt_medication = trim($data-> misc_humpty_dumpty_assmnt_medication);
$misc_humpty_dumpty_assmnt_medication_dtls = trim($data-> misc_humpty_dumpty_assmnt_medication_dtls);
$misc_nursing_assmnt = trim($data-> misc_nursing_assmnt);
$misc_nursing_diagnosis = trim($data-> misc_nursing_diagnosis);
$misc_nursing_planning = trim($data-> misc_nursing_planning);
$misc_nursing_implementation = trim($data-> misc_nursing_implementation);
$misc_nursing_evaluation = trim($data-> misc_nursing_evaluation);
$cost_center = trim($data-> cost_center);
try {
if(!empty($accesskey) && !empty($admission_num)){
//Check User Access Start
$check = $pdoread-> prepare("SELECT `userid`,`username`,`cost_center` FROM `user_logins` WHERE `mobile_accesskey` = :accesskey AND `status` = 'Active'");
$check->bindParam(':accesskey', $accesskey, PDO::PARAM_STR);
$check -> execute();
$result = $check->fetch(PDO::FETCH_ASSOC);  
if($check -> rowCount() > 0){

            //check patient discharged or not on ip
            $check_ip=$pdoread->prepare("SELECT `admissionno` FROM `registration` WHERE `admissionstatus` NOT IN('Discharged') AND `status`='Visible' AND `admissionno`=:ipno ");
            $check_ip->bindParam(':ipno', $admission_num, PDO::PARAM_STR);
            $check_ip->execute();
            if($check_ip->rowCount() > 0) {


  //check if data exists already
$admissionno_check=$pdoread->prepare("SELECT `admission_num` FROM `nursing_pediatric_init_assmnt_table` WHERE `admission_num`=:admission_num AND `cost_center`=:costcenter AND `estatus`='Active' ");
$admissionno_check->bindParam(':admission_num', $admission_num, PDO::PARAM_STR);
$admissionno_check->bindParam(':costcenter', $result['cost_center'], PDO::PARAM_STR);
$admissionno_check->execute();
if($admissionno_check->rowCount()>0){
	$response['error']=true;
	$response['message']="Data Added Previously on ".$admission_num;
}else{

$nid=$pdoread->prepare("SELECT IFNULL(MAX(`nursingid`),CONCAT('NID',DATE_FORMAT(CURRENT_DATE,'%y%m'),'000000')) AS nursingid FROM `nursing_pediatric_init_assmnt_table` WHERE `nursingid` LIKE '%NID%' ");
$nid->execute();
if($nid->rowCount()>0){
	$res=$nid->fetch(PDO::FETCH_ASSOC);
    $nursing=$res['nursingid'];
	$nursingid=++$nursing;
//nursing id created
//insert into the table
$insert = $pdo4->prepare("INSERT IGNORE INTO `nursing_pediatric_init_assmnt_table`(`sno`, `admission_num`, `umr_no`, `nursingid`, `total_fall_risk`, `total_humpty`, `phy_rec_time_ward`, `compl_time`, `delta_time`, `ad_admission_mode`, `ad_admission_mode_other`, `ad_info_obtained_form`, `ad_info_obtained_form_other`, `ad_child_accompanied`, `ad_child_accompanied_other`, `ad_babies_head_circumference`, `ad_babies_birth_weight`,  `ad_language_spoken`, `ad_language_spoken_other`, `ad_school_grade`, `ad_favorite_toy_hobbies`, `ad_vs_temperature`, `ad_vs_respiration`,  `ad_vs_blood_pressur`, `ad_vs_pulse`, `ad_vs_spo2`, `ad_vs_Weight`, `ad_vs_height`, `ad_orientation_unit`, `ad_patient_right_responsibilities`, `ad_patient_right_responsibilities_other`, `ad_ve_brought_hospital`, `ad_ve_given_name`, `ad_ve_given_name_dtls`, `ad_ve_relation`, `ad_ve_relation_dtls`, `hh_health_problems`, `hh_health_problems_other`, `hh_health_problems_ifany_identified`, `hh_health_problems_ifany_identified_dtls`, `hh_health_problems_surgeries`, `hh_health_problems_surgeries_dtls`, `hh_health_problems_chickenpox`, `hh_health_problems_chickenpox_date`, `hh_health_problems_tb`, `hh_health_problems_tb_date`, `hh_health_problems_pertussis`, `hh_health_problems_pertussis_date`, `hh_health_problems_meningitis`, `hh_health_problems_meningitis_date`, `hh_health_problems_influenza`, `hh_health_problems_influenza_date`, `hh_health_problems_immunization_uptodate`, `hh_health_problems_immunization_unsure`, `hh_health_problems_immunization_no`, `hh_allergies`, `hh_allergies_dtls`, `hh_medication_history_disposition_med`, `hh_medication_history_disposition_med_home`, `hh_medication_history_disposition_med_dose_freq`, `hh_medication_history_last_dose`, `hh_sleep_rest`, `hh_psycho`, `hh_psycho_other`, `hh_psycho_living`, `hh_psycho_relationship`, `hh_psycho_phone`, `hh_psycho_people_living_with`, `hh_psycho_father_occup`, `hh_psycho_insurance`, `hh_religious`, `hh_religious_other`, `hh_religious_any_other`, `hh_religious_cul_practices`, `hh_religious_cul_practices_dtls`, `hh_gd_past_weights`, `hh_gd_past_heights`, `hh_gd_dm_socialsmile`,  `hh_gd_dm_socialsmile_comments`, `hh_gd_dm_teething`, `hh_gd_dm_teething_comments`, `hh_gd_dm_unsupported`,  `hh_gd_dm_unsupported_comments`, `hh_gd_dm_walked`,  `hh_gd_dm_walked_comments`, `hh_gd_dm_usedwords`,  `hh_gd_dm_usedwords_comments`, `hh_gd_dm_usedsentences`, `hh_gd_dm_usedsentences_comments`, `hh_gd_dm_toliettraining`,  `hh_gd_dm_toliettraining_comments`, `hh_gd_dm_puberty`, `hh_gd_dm_puberty_comments`, `hh_pain_scale_used`, `hh_pain_patient_expresses`, `misc_nutrition_needs_res_feeding_breast_feeding`, `misc_nutrition_needs_res_feeding_breast_frequency`, `misc_nutrition_needs_res_feeding_breast_duration`, `misc_nutrition_needs_res_feeding_breast_na`, `misc_nutrition_needs_res_feeding_breast_solids`, `misc_nutrition_needs_res_feeding_bottle`, `misc_nutrition_needs_res_feeding_bottle_type`, `misc_nutrition_needs_res_feeding_bottle_amount`, `misc_nutrition_needs_res_feeding_bottle_frequency`, `misc_nutrition_needs_res_feeding_bottle_na`, `misc_nutrition_needs_res_feeding_tube`, `misc_nutrition_needs_res_feeding_tube_type`, `misc_nutrition_needs_res_feeding_tube_amount`, `misc_nutrition_needs_res_feeding_tube_frequency`, `misc_nutrition_needs_res_feeding_tube_na`, `misc_nutrition_needs_assistance_feeding`, `misc_nutrition_needs_appetite`, `misc_nutrition_needs_risk`, `misc_func_assmnt_cat_feeding_score`, `misc_func_assmnt_cat_feeding_other`, `misc_func_assmnt_cat_toileting_score`, `misc_func_assmnt_cat_toileting_other`, `misc_func_assmnt_cat_dressing_score`, `misc_func_assmnt_cat_dressing_other`, `misc_func_assmnt_cat_groomming_score`, `misc_func_assmnt_cat_groomming_other`, `misc_func_assmnt_cat_walking_score`, `misc_func_assmnt_cat_walking_other`, `misc_func_assmnt_cat_transfer_score`, `misc_func_assmnt_cat_transfer_other`, `misc_func_assmnt_cat_mobility_score`, `misc_func_assmnt_cat_mobility_other`, `misc_func_assmnt_cat_mobility_changes`, `misc_func_assmnt_cat_mobility_discribe`, `misc_educational_assmnt`, `misc_skin_risk_assmnt_sensory`, `misc_skin_risk_assmnt_sensory_dtls`, `misc_skin_risk_assmnt_moisture`, `misc_skin_risk_assmnt_moisture_dtls`, `misc_skin_risk_assmnt_activity`, `misc_skin_risk_assmnt_activity_dtls`, `misc_skin_risk_assmnt_mobility`, `misc_skin_risk_assmnt_mobility_dtls`, `misc_skin_risk_assmnt_nutrition`, `misc_skin_risk_assmnt_nutrition_dtls`, `misc_skin_risk_assmnt_friction`, `misc_skin_risk_assmnt_friction_dtls`, `misc_flacc_pain_assmnt_face`,  `misc_humpty_dumpty_assmnt_age`, `misc_humpty_dumpty_assmnt_age_dtls`, `misc_humpty_dumpty_assmnt_gender`, `misc_humpty_dumpty_assmnt_gender_dtls`, `misc_humpty_dumpty_assmnt_diagnosis`, `misc_humpty_dumpty_assmnt_diagnosis_dtls`, `misc_humpty_dumpty_assmnt_cognitive`, `misc_humpty_dumpty_assmnt_congnitive_dtls`, `misc_humpty_dumpty_assmnt_envfactors`, `misc_humpty_dumpty_assmnt_envfactors_dtls`, `misc_humpty_dumpty_assmnt_surgery`, `misc_humpty_dumpty_assmnt_surgery_dtls`, `misc_humpty_dumpty_assmnt_medication`, `misc_humpty_dumpty_assmnt_medication_dtls`, `misc_nursing_assmnt`, `misc_nursing_diagnosis`, `misc_nursing_planning`, `misc_nursing_implementation`, `misc_nursing_evaluation`, `cost_center`, `created_on`, `created_by`, `modified_on`, `modified_by`, `estatus`,`bmi_value`) VALUES(NULL, :admission_num, :umr_no, :nursingid, :total_fall_risk, :total_humpty, :phy_rec_time_ward, :compl_time, :delta_time, :ad_admission_mode, :ad_admission_mode_other, :ad_info_obtained_form, :ad_info_obtained_form_other, :ad_child_accompanied, :ad_child_accompanied_other, :ad_babies_head_circumference,  :ad_babies_birth_weight,  :ad_language_spoken, :ad_language_spoken_other, :ad_school_grade, :ad_favorite_toy_hobbies, :ad_vs_temperature,  :ad_vs_respiration,  :ad_vs_blood_pressur, :ad_vs_pulse,  :ad_vs_spo2, :ad_vs_Weight, :ad_vs_height,  :ad_orientation_unit, :ad_patient_right_responsibilities, :ad_patient_right_responsibilities_other, :ad_ve_brought_hospital, :ad_ve_given_name, :ad_ve_given_name_dtls, :ad_ve_relation, :ad_ve_relation_dtls, :hh_health_problems, :hh_health_problems_other, :hh_health_problems_ifany_identified, :hh_health_problems_ifany_identified_dtls, :hh_health_problems_surgeries, :hh_health_problems_surgeries_dtls, :hh_health_problems_chickenpox, :hh_health_problems_chickenpox_date, :hh_health_problems_tb, :hh_health_problems_tb_date, :hh_health_problems_pertussis, :hh_health_problems_pertussis_date, :hh_health_problems_meningitis, :hh_health_problems_meningitis_date, :hh_health_problems_influenza, :hh_health_problems_influenza_date, :hh_health_problems_immunization_uptodate, :hh_health_problems_immunization_unsure, :hh_health_problems_immunization_no, :hh_allergies, :hh_allergies_dtls, :hh_medication_history_disposition_med, :hh_medication_history_disposition_med_home, :hh_medication_history_disposition_med_dose_freq, :hh_medication_history_last_dose, :hh_sleep_rest, :hh_psycho, :hh_psycho_other, :hh_psycho_living, :hh_psycho_relationship, :hh_psycho_phone, :hh_psycho_people_living_with, :hh_psycho_father_occup, :hh_psycho_insurance, :hh_religious, :hh_religious_other, :hh_religious_any_other, :hh_religious_cul_practices, :hh_religious_cul_practices_dtls, :hh_gd_past_weights, :hh_gd_past_heights, :hh_gd_dm_socialsmile, :hh_gd_dm_socialsmile_comments,:hh_gd_dm_teething, :hh_gd_dm_teething_comments, :hh_gd_dm_unsupported, :hh_gd_dm_unsupported_comments, :hh_gd_dm_walked, :hh_gd_dm_walked_comments, :hh_gd_dm_usedwords, :hh_gd_dm_usedwords_comments, :hh_gd_dm_usedsentences, :hh_gd_dm_usedsentences_comments, :hh_gd_dm_toliettraining, :hh_gd_dm_toliettraining_comments, :hh_gd_dm_puberty, :hh_gd_dm_puberty_comments, :hh_pain_scale_used, :hh_pain_patient_expresses, :misc_nutrition_needs_res_feeding_breast_feeding, :misc_nutrition_needs_res_feeding_breast_frequency, :misc_nutrition_needs_res_feeding_breast_duration, :misc_nutrition_needs_res_feeding_breast_na, :misc_nutrition_needs_res_feeding_breast_solids, :misc_nutrition_needs_res_feeding_bottle, :misc_nutrition_needs_res_feeding_bottle_type, :misc_nutrition_needs_res_feeding_bottle_amount, :misc_nutrition_needs_res_feeding_bottle_frequency, :misc_nutrition_needs_res_feeding_bottle_na, :misc_nutrition_needs_res_feeding_tube, :misc_nutrition_needs_res_feeding_tube_type, :misc_nutrition_needs_res_feeding_tube_amount, :misc_nutrition_needs_res_feeding_tube_frequency, :misc_nutrition_needs_res_feeding_tube_na, :misc_nutrition_needs_assistance_feeding, :misc_nutrition_needs_appetite, :misc_nutrition_needs_risk, :misc_func_assmnt_cat_feeding_score, :misc_func_assmnt_cat_feeding_other, :misc_func_assmnt_cat_toileting_score, :misc_func_assmnt_cat_toileting_other, :misc_func_assmnt_cat_dressing_score, :misc_func_assmnt_cat_dressing_other, :misc_func_assmnt_cat_groomming_score, :misc_func_assmnt_cat_groomming_other, :misc_func_assmnt_cat_walking_score, :misc_func_assmnt_cat_walking_other, :misc_func_assmnt_cat_transfer_score, :misc_func_assmnt_cat_transfer_other, :misc_func_assmnt_cat_mobility_score, :misc_func_assmnt_cat_mobility_other, :misc_func_assmnt_cat_mobility_changes, :misc_func_assmnt_cat_mobility_discribe, :misc_educational_assmnt, :misc_skin_risk_assmnt_sensory, :misc_skin_risk_assmnt_sensory_dtls, :misc_skin_risk_assmnt_moisture, :misc_skin_risk_assmnt_moisture_dtls, :misc_skin_risk_assmnt_activity, :misc_skin_risk_assmnt_activity_dtls, :misc_skin_risk_assmnt_mobility, :misc_skin_risk_assmnt_mobility_dtls, :misc_skin_risk_assmnt_nutrition, :misc_skin_risk_assmnt_nutrition_dtls, :misc_skin_risk_assmnt_friction, :misc_skin_risk_assmnt_friction_dtls, :misc_flacc_pain_assmnt_face,  :misc_humpty_dumpty_assmnt_age, :misc_humpty_dumpty_assmnt_age_dtls, :misc_humpty_dumpty_assmnt_gender, :misc_humpty_dumpty_assmnt_gender_dtls, :misc_humpty_dumpty_assmnt_diagnosis, :misc_humpty_dumpty_assmnt_diagnosis_dtls, :misc_humpty_dumpty_assmnt_cognitive, :misc_humpty_dumpty_assmnt_congnitive_dtls, :misc_humpty_dumpty_assmnt_envfactors, :misc_humpty_dumpty_assmnt_envfactors_dtls, :misc_humpty_dumpty_assmnt_surgery, :misc_humpty_dumpty_assmnt_surgery_dtls, :misc_humpty_dumpty_assmnt_medication, :misc_humpty_dumpty_assmnt_medication_dtls, :misc_nursing_assmnt, :misc_nursing_diagnosis, :misc_nursing_planning, :misc_nursing_implementation, :misc_nursing_evaluation, :cost_center, CURRENT_TIMESTAMP,:userid,CURRENT_TIMESTAMP, :userid, 'Active',:bmi_value)");
$insert->bindParam(':bmi_value',$bmi_value,PDO::PARAM_STR);
$insert->bindParam(':admission_num',$admission_num,PDO::PARAM_STR);
$insert->bindParam(':umr_no',$umr_no,PDO::PARAM_STR);
$insert->bindParam(':nursingid',$nursingid,PDO::PARAM_STR);
$insert->bindParam(':total_fall_risk',$total_fall_risk,PDO::PARAM_STR);
$insert->bindParam(':total_humpty',$total_humpty,PDO::PARAM_STR);
$insert->bindParam(':phy_rec_time_ward',$phy_rec_time_ward,PDO::PARAM_STR);
$insert->bindParam(':compl_time',$compl_time,PDO::PARAM_STR);
$insert->bindParam(':delta_time',$delta_time,PDO::PARAM_STR);
$insert->bindParam(':ad_admission_mode',$ad_admission_mode,PDO::PARAM_STR);
$insert->bindParam(':ad_admission_mode_other',$ad_admission_mode_other,PDO::PARAM_STR);
$insert->bindParam(':ad_info_obtained_form',$ad_info_obtained_form,PDO::PARAM_STR);
$insert->bindParam(':ad_info_obtained_form_other',$ad_info_obtained_form_other,PDO::PARAM_STR);
$insert->bindParam(':ad_child_accompanied',$ad_child_accompanied,PDO::PARAM_STR);
$insert->bindParam(':ad_child_accompanied_other',$ad_child_accompanied_other,PDO::PARAM_STR);
$insert->bindParam(':ad_babies_head_circumference',$ad_babies_head_circumference,PDO::PARAM_STR);
$insert->bindParam(':ad_babies_birth_weight',$ad_babies_birth_weight,PDO::PARAM_STR);
$insert->bindParam(':ad_language_spoken',$ad_language_spoken,PDO::PARAM_STR);
$insert->bindParam(':ad_language_spoken_other',$ad_language_spoken_other,PDO::PARAM_STR);
$insert->bindParam(':ad_school_grade',$ad_school_grade,PDO::PARAM_STR);
$insert->bindParam(':ad_favorite_toy_hobbies',$ad_favorite_toy_hobbies,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_temperature',$ad_vs_temperature,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_respiration',$ad_vs_respiration,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_blood_pressur',$ad_vs_blood_pressur,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_pulse',$ad_vs_pulse,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_spo2',$ad_vs_spo2,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_Weight',$ad_vs_Weight,PDO::PARAM_STR);
$insert->bindParam(':ad_vs_height',$ad_vs_height,PDO::PARAM_STR);
$insert->bindParam(':ad_orientation_unit',$ad_orientation_unit,PDO::PARAM_STR);
$insert->bindParam(':ad_patient_right_responsibilities',$ad_patient_right_responsibilities,PDO::PARAM_STR);
$insert->bindParam(':ad_patient_right_responsibilities_other',$ad_patient_right_responsibilities_other,PDO::PARAM_STR);
$insert->bindParam(':ad_ve_brought_hospital',$ad_ve_brought_hospital,PDO::PARAM_STR);
$insert->bindParam(':ad_ve_given_name',$ad_ve_given_name,PDO::PARAM_STR);
$insert->bindParam(':ad_ve_given_name_dtls',$ad_ve_given_name_dtls,PDO::PARAM_STR);
$insert->bindParam(':ad_ve_relation',$ad_ve_relation,PDO::PARAM_STR);
$insert->bindParam(':ad_ve_relation_dtls',$ad_ve_relation_dtls,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems',$hh_health_problems,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_other',$hh_health_problems_other,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_ifany_identified',$hh_health_problems_ifany_identified,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_ifany_identified_dtls',$hh_health_problems_ifany_identified_dtls,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_surgeries',$hh_health_problems_surgeries,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_surgeries_dtls',$hh_health_problems_surgeries_dtls,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_chickenpox',$hh_health_problems_chickenpox,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_chickenpox_date',$hh_health_problems_chickenpox_date,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_tb',$hh_health_problems_tb,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_tb_date',$hh_health_problems_tb_date,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_pertussis',$hh_health_problems_pertussis,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_pertussis_date',$hh_health_problems_pertussis_date,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_meningitis',$hh_health_problems_meningitis,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_meningitis_date',$hh_health_problems_meningitis_date,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_influenza',$hh_health_problems_influenza,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_influenza_date',$hh_health_problems_influenza_date,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_immunization_uptodate',$hh_health_problems_immunization_uptodate,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_immunization_unsure',$hh_health_problems_immunization_unsure,PDO::PARAM_STR);
$insert->bindParam(':hh_health_problems_immunization_no',$hh_health_problems_immunization_no,PDO::PARAM_STR);
$insert->bindParam(':hh_allergies',$hh_allergies,PDO::PARAM_STR);
$insert->bindParam(':hh_allergies_dtls',$hh_allergies_dtls,PDO::PARAM_STR);
$insert->bindParam(':hh_medication_history_disposition_med',$hh_medication_history_disposition_med,PDO::PARAM_STR);
$insert->bindParam(':hh_medication_history_disposition_med_home',$hh_medication_history_disposition_med_home,PDO::PARAM_STR);
$insert->bindParam(':hh_medication_history_disposition_med_dose_freq',$hh_medication_history_disposition_med_dose_freq,PDO::PARAM_STR);
$insert->bindParam(':hh_medication_history_last_dose',$hh_medication_history_last_dose,PDO::PARAM_STR);
$insert->bindParam(':hh_sleep_rest',$hh_sleep_rest,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho',$hh_psycho,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_other',$hh_psycho_other,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_living',$hh_psycho_living,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_relationship',$hh_psycho_relationship,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_phone',$hh_psycho_phone,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_people_living_with',$hh_psycho_people_living_with,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_father_occup',$hh_psycho_father_occup,PDO::PARAM_STR);
$insert->bindParam(':hh_psycho_insurance',$hh_psycho_insurance,PDO::PARAM_STR);
$insert->bindParam(':hh_religious',$hh_religious,PDO::PARAM_STR);
$insert->bindParam(':hh_religious_other',$hh_religious_other,PDO::PARAM_STR);
$insert->bindParam(':hh_religious_any_other',$hh_religious_any_other,PDO::PARAM_STR);
$insert->bindParam(':hh_religious_cul_practices',$hh_religious_cul_practices,PDO::PARAM_STR);
$insert->bindParam(':hh_religious_cul_practices_dtls',$hh_religious_cul_practices_dtls,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_past_weights',$hh_gd_past_weights,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_past_heights',$hh_gd_past_heights,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_socialsmile',$hh_gd_dm_socialsmile,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_socialsmile_comments',$hh_gd_dm_socialsmile_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_teething',$hh_gd_dm_teething,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_teething_comments',$hh_gd_dm_teething_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_unsupported',$hh_gd_dm_unsupported,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_unsupported_comments',$hh_gd_dm_unsupported_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_walked',$hh_gd_dm_walked,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_walked_comments',$hh_gd_dm_walked_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_usedwords',$hh_gd_dm_usedwords,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_usedwords_comments',$hh_gd_dm_usedwords_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_usedsentences',$hh_gd_dm_usedsentences,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_usedsentences_comments',$hh_gd_dm_usedsentences_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_toliettraining',$hh_gd_dm_toliettraining,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_toliettraining_comments',$hh_gd_dm_toliettraining_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_puberty',$hh_gd_dm_puberty,PDO::PARAM_STR);
$insert->bindParam(':hh_gd_dm_puberty_comments',$hh_gd_dm_puberty_comments,PDO::PARAM_STR);
$insert->bindParam(':hh_pain_scale_used',$hh_pain_scale_used,PDO::PARAM_STR);
$insert->bindParam(':hh_pain_patient_expresses',$hh_pain_patient_expresses,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_breast_feeding',$misc_nutrition_needs_res_feeding_breast_feeding,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_breast_frequency',$misc_nutrition_needs_res_feeding_breast_frequency,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_breast_duration',$misc_nutrition_needs_res_feeding_breast_duration,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_breast_na',$misc_nutrition_needs_res_feeding_breast_na,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_breast_solids',$misc_nutrition_needs_res_feeding_breast_solids,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_bottle',$misc_nutrition_needs_res_feeding_bottle,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_bottle_type',$misc_nutrition_needs_res_feeding_bottle_type,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_bottle_amount',$misc_nutrition_needs_res_feeding_bottle_amount,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_bottle_frequency',$misc_nutrition_needs_res_feeding_bottle_frequency,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_bottle_na',$misc_nutrition_needs_res_feeding_bottle_na,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_tube',$misc_nutrition_needs_res_feeding_tube,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_tube_type',$misc_nutrition_needs_res_feeding_tube_type,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_tube_amount',$misc_nutrition_needs_res_feeding_tube_amount,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_tube_frequency',$misc_nutrition_needs_res_feeding_tube_frequency,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_res_feeding_tube_na',$misc_nutrition_needs_res_feeding_tube_na,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_assistance_feeding',$misc_nutrition_needs_assistance_feeding,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_appetite',$misc_nutrition_needs_appetite,PDO::PARAM_STR);
$insert->bindParam(':misc_nutrition_needs_risk',$misc_nutrition_needs_risk,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_feeding_score',$misc_func_assmnt_cat_feeding_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_feeding_other',$misc_func_assmnt_cat_feeding_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_toileting_score',$misc_func_assmnt_cat_toileting_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_toileting_other',$misc_func_assmnt_cat_toileting_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_dressing_score',$misc_func_assmnt_cat_dressing_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_dressing_other',$misc_func_assmnt_cat_dressing_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_groomming_score',$misc_func_assmnt_cat_groomming_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_groomming_other',$misc_func_assmnt_cat_groomming_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_walking_score',$misc_func_assmnt_cat_walking_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_walking_other',$misc_func_assmnt_cat_walking_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_transfer_score',$misc_func_assmnt_cat_transfer_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_transfer_other',$misc_func_assmnt_cat_transfer_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_mobility_score',$misc_func_assmnt_cat_mobility_score,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_mobility_other',$misc_func_assmnt_cat_mobility_other,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_mobility_changes',$misc_func_assmnt_cat_mobility_changes,PDO::PARAM_STR);
$insert->bindParam(':misc_func_assmnt_cat_mobility_discribe',$misc_func_assmnt_cat_mobility_discribe,PDO::PARAM_STR);
$insert->bindParam(':misc_educational_assmnt',$misc_educational_assmnt,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_sensory',$misc_skin_risk_assmnt_sensory,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_sensory_dtls',$misc_skin_risk_assmnt_sensory_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_moisture',$misc_skin_risk_assmnt_moisture,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_moisture_dtls',$misc_skin_risk_assmnt_moisture_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_activity',$misc_skin_risk_assmnt_activity,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_activity_dtls',$misc_skin_risk_assmnt_activity_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_mobility',$misc_skin_risk_assmnt_mobility,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_mobility_dtls',$misc_skin_risk_assmnt_mobility_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_nutrition',$misc_skin_risk_assmnt_nutrition,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_nutrition_dtls',$misc_skin_risk_assmnt_nutrition_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_friction',$misc_skin_risk_assmnt_friction,PDO::PARAM_STR);
$insert->bindParam(':misc_skin_risk_assmnt_friction_dtls',$misc_skin_risk_assmnt_friction_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_flacc_pain_assmnt_face',$misc_flacc_pain_assmnt_face,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_age',$misc_humpty_dumpty_assmnt_age,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_age_dtls',$misc_humpty_dumpty_assmnt_age_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_gender',$misc_humpty_dumpty_assmnt_gender,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_gender_dtls',$misc_humpty_dumpty_assmnt_gender_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_diagnosis',$misc_humpty_dumpty_assmnt_diagnosis,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_diagnosis_dtls',$misc_humpty_dumpty_assmnt_diagnosis_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_cognitive',$misc_humpty_dumpty_assmnt_cognitive,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_congnitive_dtls',$misc_humpty_dumpty_assmnt_congnitive_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_envfactors',$misc_humpty_dumpty_assmnt_envfactors,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_envfactors_dtls',$misc_humpty_dumpty_assmnt_envfactors_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_surgery',$misc_humpty_dumpty_assmnt_surgery,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_surgery_dtls',$misc_humpty_dumpty_assmnt_surgery_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_medication',$misc_humpty_dumpty_assmnt_medication,PDO::PARAM_STR);
$insert->bindParam(':misc_humpty_dumpty_assmnt_medication_dtls',$misc_humpty_dumpty_assmnt_medication_dtls,PDO::PARAM_STR);
$insert->bindParam(':misc_nursing_assmnt',$misc_nursing_assmnt,PDO::PARAM_STR);
$insert->bindParam(':misc_nursing_diagnosis',$misc_nursing_diagnosis,PDO::PARAM_STR);
$insert->bindParam(':misc_nursing_planning',$misc_nursing_planning,PDO::PARAM_STR);
$insert->bindParam(':misc_nursing_implementation',$misc_nursing_implementation,PDO::PARAM_STR);
$insert->bindParam(':misc_nursing_evaluation',$misc_nursing_evaluation,PDO::PARAM_STR);
$insert->bindParam(':cost_center',$cost_center,PDO::PARAM_STR);
$insert->bindParam(':userid', $result['userid'], PDO::PARAM_STR);
$insert->execute();
        if($insert-> rowCount() > 0){
            $response['error'] = false;
          $response['message']= "Data Inserted Successfully";
         
          }else{
              $response['error'] = true;
              $response['message']= "Data Not Inserted";
          }
        }else{
          $response['error']=true;
          $response['message']="Nursing Id generation Failed";
        }   
      }     
//Check User Access End
    }else{
      $response["error"] = true;
      $response["message"]= "Patient Checked Out";
    }
}else{
    $response['error'] = true;
      $response['message']= "Access Denied";
  }
}else{
	$response['error'] = true;
	$response['message']= "Sorry! some details are missing";
}
//Check empty Parameters End
} catch(PDOException $e) {
	http_response_code(503);
	$response['error'] = true;
	$response['message']= "Connection failed".$e->getMessage();;
}
echo json_encode($response);
$pdo4= null;
$pdoread= null;
?>
