<?php
function radiologyworklist($con,$billno,$userid,$patienttype,$branch){
$radiology = $con->prepare("INSERT INTO `rad_worklist`(`sno`, `rad_no`, `service_category`, `machine_short_code`, `cost_center`, `consultantname`, `patientname`, `umrno`, `dob`, `age`, `patient_gender`, `billno`, `requisition_no`, `total`, `services`, `servicecode`, `servicegroupcode`, `admissionno`, `mchn_code`, `patient_type`, `rec_type`, `bill_status`, `status`, `createdby`, `createdon`, `modified_by`, `modified_on`, `bill_date`) (SELECT NULL,'',R.service_category,R.machine_short_code,R.cost_center,R.refreral_doctor AS refreral_doctor,CONCAT(`umr_registration`.`title`,'. ',R.patient_name) AS patient_name,R.umrno,DATE_FORMAT(umr_registration.patient_age,'%Y%m%d') AS dob,(CASE WHEN  TIMESTAMPDIFF(YEAR, `umr_registration`.`patient_age`, now())!='0' THEN CONCAT('0',TIMESTAMPDIFF(YEAR, `umr_registration`.`patient_age`, now()),'Y') WHEN  TIMESTAMPDIFF( MONTH,`umr_registration`.`patient_age`, now() ) % 12 !='0' THEN  CONCAT('0',TIMESTAMPDIFF( MONTH, `umr_registration`.`patient_age`, now() ) % 12,'M') WHEN FLOOR( TIMESTAMPDIFF( DAY, `umr_registration`.`patient_age`, now() ) % 30.4375 )!='0' THEN CONCAT('0',FLOOR( TIMESTAMPDIFF( DAY, `umr_registration`.`patient_age`, now() ) % 30.4375 ),'D') ELSE 0 END) AS age,`umr_registration`.`patient_gender`,R.billno,R.requisition_no,R.total,R.services,R.servicecode,R.servicegroupcode,R.admissionno,R.msncode,R.patient_type,R.rec_type,R.billstatus,R.sstatus,R.createdby,R.createdon,R.modifiedby,R.modifiedon,R.billdate FROM (SELECT `department_servicegroup_master`.`service_category`,`department_servicegroup_master`.`machine_short_code`,`op_billing_generate`.`cost_center`,`op_biling_history`.`refreral_doctor`,`op_billing_generate`.`patient_name`,`op_billing_generate`.`umrno`,'' AS age,'' AS gender,`op_biling_history`.`billno`,`op_biling_history`.`requisition_no`,`op_biling_history`.`total`,`op_biling_history`.`services`,`op_biling_history`.`servicecode`,`op_biling_history`.`servicegroupcode`,'' AS admissionno,`machine_master_new`.`mchn_code` AS msncode,:patienttype AS patient_type,'OPD' AS rec_type,'B' AS billstatus,'A' AS sstatus,:userid AS createdby,CURRENT_TIMESTAMP AS createdon,'' AS modifiedby,'0000-00-00 00:00:00' AS modifiedon,`op_biling_history`.`modifiedon` AS billdate FROM `op_biling_history` LEFT JOIN `op_billing_generate` ON `op_billing_generate`.`inv_no` = `op_biling_history`.`billno` LEFT JOIN `department_servicegroup_master` ON `department_servicegroup_master`.`service_groupcode` = `op_biling_history`.`servicegroupcode` LEFT JOIN `machine_master_new` ON `machine_master_new`.mchn_shortname= `department_servicegroup_master`.machine_short_code AND `machine_master_new`.`cost_center` =:branch WHERE TRIM(`op_biling_history`.`category`)IN (TRIM('RADIOLOGY'),TRIM('CARDIOLOGY')) AND `op_biling_history`.`billno` = :billno AND `op_biling_history`.`status` = 'Visible') AS R LEFT JOIN `umr_registration` ON `umr_registration`.`umrno` = R.umrno)");
	$radiology->bindParam(':billno', $billno, PDO::PARAM_STR);
	$radiology->bindParam(':userid', $userid, PDO::PARAM_STR);
	$radiology->bindParam(':patienttype', $patienttype, PDO::PARAM_STR);
	$radiology->bindParam(':branch', $branch, PDO::PARAM_STR);
	$radiology->execute();
if($radiology -> rowCount() > 0){
$response = 'Data Saved';
}else{
    $response = 'Data not saved';
}
return $response;
}
//ipradiologyworklist($con,$billno,$userid,$patienttype);
function ipradiologyworklist($con,$billno,$userid,$patienttype){
	$radiology = $con->prepare("INSERT IGNORE INTO `rad_worklist`(`sno`, `rad_no`, `service_category`, `machine_short_code`, `cost_center`, `consultantname`, `patientname`, `umrno`, `dob`, `age`, `patient_gender`, `billno`, `requisition_no`, `total`, `services`, `servicecode`, `servicegroupcode`, `admissionno`, `mchn_code`, `patient_type`, `rec_type`, `bill_status`, `status`, `createdby`, `createdon`, `modified_by`, `modified_on`, `bill_date`) (SELECT NULL,'',R.service_category,R.machine_short_code,R.cost_center,R.refreral_doctor AS refreral_doctor,CONCAT(`umr_registration`.`title`,'. ',R.patient_name) AS patient_name,R.umrno,DATE_FORMAT(umr_registration.patient_age,'%Y%m%d') AS dob,(CASE WHEN  TIMESTAMPDIFF(YEAR, `umr_registration`.`patient_age`, now())!='0' THEN CONCAT('0',TIMESTAMPDIFF(YEAR, `umr_registration`.`patient_age`, now()),'Y') WHEN  TIMESTAMPDIFF( MONTH,`umr_registration`.`patient_age`, now() ) % 12 !='0' THEN  CONCAT('0',TIMESTAMPDIFF( MONTH, `umr_registration`.`patient_age`, now() ) % 12,'M') WHEN FLOOR( TIMESTAMPDIFF( DAY, `umr_registration`.`patient_age`, now() ) % 30.4375 )!='0' THEN CONCAT('0',FLOOR( TIMESTAMPDIFF( DAY, `umr_registration`.`patient_age`, now() ) % 30.4375 ),'D') ELSE 0 END) AS age,`umr_registration`.`patient_gender`,R.billno,R.requisition_no,R.total,R.services,R.servicecode,R.servicegroupcode,R.admissionno,R.msncode,R.patient_type,R.rec_type,R.billstatus,R.sstatus,R.createdby,R.createdon,R.modifiedby,R.modifiedon,R.billdate FROM (SELECT `department_servicegroup_master`.`service_category`,`department_servicegroup_master`.`machine_short_code`,`registration`.`cost_center`,'' AS refreral_doctor,`registration`.`patientname` AS patient_name,`registration`.`umrno`,'' AS age,'' AS gender,`billing_history`.`billno`,`billing_history`.`requisition_no`,`billing_history`.`total`,`billing_history`.`services`,`billing_history`.`servicecode`,`billing_history`.`servicegroupcode`,`billing_history`.`ipno` AS admissionno,`machine_master_new`.`mchn_code` AS msncode,:patienttype AS patient_type,'IPD' AS rec_type,'B' AS billstatus,'A' AS sstatus,:userid AS createdby,CURRENT_TIMESTAMP AS createdon,:userid AS modifiedby,'0000-00-00 00:00:00' AS modifiedon,`billing_history`.`modifiedon` AS billdate FROM `billing_history` LEFT JOIN `registration` ON `registration`.`admissionno` = `billing_history`.`ipno` LEFT JOIN `department_servicegroup_master` ON `department_servicegroup_master`.`service_groupcode` = `billing_history`.`servicegroupcode` LEFT JOIN `machine_master_new` ON `machine_master_new`.mchn_shortname= `department_servicegroup_master`.machine_short_code  AND `machine_master_new`.`cost_center` = `billing_history`.`costcenter` WHERE TRIM(`billing_history`.`category`)IN(TRIM('RADIOLOGY'),TRIM('CARDIOLOGY'),TRIM('INTERVENTIONAL RADIOLOGY')) AND `billing_history`.`ipno` = :billno AND `billing_history`.`status` IN ('Hold')) AS R LEFT JOIN `umr_registration` ON `umr_registration`.`umrno` = R.umrno)");
		$radiology->bindParam(':billno', $billno, PDO::PARAM_STR);
		$radiology->bindParam(':userid', $userid, PDO::PARAM_STR);
		$radiology->bindParam(':patienttype', $patienttype, PDO::PARAM_STR);
		$radiology->execute();
	if($radiology -> rowCount() > 0){
	$response2 = 'Data Saved';
	}else{
		$response2 = 'Data not saved';
	}
	return $response2;
	}
	//health check up
function healthcheckrad($con,$billno,$userid,$patienttype,$branch){
	$radiology = $con->prepare("INSERT IGNORE INTO `rad_worklist`(`sno`, `rad_no`, `service_category`, `machine_short_code`, `cost_center`, `consultantname`, `patientname`, `umrno`, `dob`, `age`, `patient_gender`, `billno`, `requisition_no`, `total`, `services`, `servicecode`, `servicegroupcode`, `admissionno`, `mchn_code`, `patient_type`, `rec_type`, `bill_status`, `status`, `createdby`, `createdon`, `modified_by`, `modified_on`, `bill_date`) (SELECT NULL, '',`department_servicegroup_master`.`service_category`,`department_servicegroup_master`.`machine_short_code`,service.costcenter,service.prescription_by,TRIM(CONCAT(`umr_registration`.`title`,'. ',`umr_registration`.`patient_name`,' ',`umr_registration`.`middle_name`, ' ',`umr_registration`.`last_name`)) AS patientname,service.`umr_no`,DATE_FORMAT(umr_registration.patient_age,'%Y%m%d') AS dob,(CASE WHEN  TIMESTAMPDIFF(YEAR, `umr_registration`.`patient_age`, now())!='0' THEN CONCAT('0',TIMESTAMPDIFF(YEAR, `umr_registration`.`patient_age`, now()),'Y') WHEN  TIMESTAMPDIFF( MONTH,`umr_registration`.`patient_age`, now() ) % 12 !='0' THEN  CONCAT('0',TIMESTAMPDIFF( MONTH, `umr_registration`.`patient_age`, now() ) % 12,'M') WHEN FLOOR( TIMESTAMPDIFF( DAY, `umr_registration`.`patient_age`, now() ) % 30.4375 )!='0' THEN CONCAT('0',FLOOR( TIMESTAMPDIFF( DAY, `umr_registration`.`patient_age`, now() ) % 30.4375 ),'D') ELSE 0 END) AS age,`umr_registration`.`patient_gender`,service.`billno`,service.`requisition_no`,service.`total`,service.`service_name`,service.`service_code`,service.`service_group_code`,'',`machine_master_new`.`mchn_code`,:patienttype,'OPD','B','A',:userid,CURRENT_TIMESTAMP,:userid,'0000-00-00 00:00:00',service.`createdon` FROM (SELECT `op_biling_history`.`costcenter`,`op_biling_history`.`prescription_by`,`op_biling_history`.`umr_no`,`op_biling_history`.`billno`,`op_biling_history`.`requisition_no`,`op_biling_history`.`total`,`package_list`.`service_name`,`package_list`.`service_code`,`services_master`.`service_group_code`,`op_biling_history`.`modifiedon` AS createdon FROM `op_biling_history` LEFT JOIN `package_list` ON `package_list`.`package_id` = `op_biling_history`.`servicecode` AND `op_biling_history`.`status` = 'Visible' LEFT JOIN `services_master` ON `package_list`.`service_code` = `services_master`.`service_code` WHERE `op_biling_history`.`billno` = :billno AND `package_list`.`service_department` IN('CARDIOLOGY','RADIOLOGY')) AS service LEFT JOIN `department_servicegroup_master` ON `department_servicegroup_master`.`service_groupcode` = service.service_group_code LEFT JOIN `machine_master_new` ON `machine_master_new`.`mchn_shortname`= `department_servicegroup_master`.machine_short_code AND `machine_master_new`.`cost_center`=:branch LEFT JOIN `umr_registration` ON `umr_registration`.`umrno` = service.`umr_no`)");
		$radiology->bindParam(':billno', $billno, PDO::PARAM_STR);
		$radiology->bindParam(':userid', $userid, PDO::PARAM_STR);
		$radiology->bindParam(':patienttype', $patienttype, PDO::PARAM_STR);
		$radiology->bindParam(':branch', $branch, PDO::PARAM_STR);
		$radiology->execute();
	if($radiology -> rowCount() > 0){
	$response5 = 'Data Saved';
	}else{
		$response5 = 'Data not saved';
	}
	return $response5;
	}
?>